'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3053
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class POCorrespondence

    '''<summary>
    '''POCorresForm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POCorresForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Msg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''POUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POUser As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''POLocation コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SOUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SOUser As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SOLocation コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SOLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CorresTitle コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CorresTitle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CorresNote コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CorresNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Send コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Send As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''POHistory コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POHistory As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''SrcPOHistory コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SrcPOHistory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''hd_PONumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hd_PONumber As Global.System.Web.UI.WebControls.HiddenField
End Class
