'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3053
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class POUpdate

    '''<summary>
    '''Head1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''POForm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Msg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFQNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RFQNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ParPONumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ParPONumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''R3PONumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3PONumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R3POLineNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3POLineNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PODate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PODate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''POUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''POLocation コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProductNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ProductNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProductName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ProductName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderQuantity コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents OrderQuantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderUnit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents OrderUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DeliveryDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DeliveryDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Currency コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Currency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UnitPrice コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UnitPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PerQuantity コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PerQuantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PerUnit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PerUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''R3SupplierCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3SupplierCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''R3SupplierName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3SupplierName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''R3MakerCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3MakerCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''R3MakerName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3MakerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PaymentTerm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PaymentTerm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Incoterms コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Incoterms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DeliveryTerm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DeliveryTerm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Purpose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Purpose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RawMaterialFor コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RawMaterialFor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RequestedBy コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RequestedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupplierItemNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierItemNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupplierLotNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierLotNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DueDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DueDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GoodsArrivedDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents GoodsArrivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LotNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LotNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''InvoceReceivedDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents InvoceReceivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ImportCustomClearanceDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ImportCustomClearanceDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMStartingDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMStartingDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMFinishDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMFinishDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMResult コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequestQuantity コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RequestQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ScheduledExportDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ScheduledExportDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PurchasingRequisitionNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PurchasingRequisitionNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CancellationDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CancellationDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChiPOIssue コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ChiPOIssue As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''UpdateDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdateDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PO As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Action コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Action As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Update コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancell コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Cancell As Global.System.Web.UI.WebControls.Button
End Class
