'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5477
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class RFQUpdate

    '''<summary>
    '''RFQForm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RFQForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Msg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFQNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RFQNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CurrentRFQStatus コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents CurrentRFQStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProductNumber コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ProductNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProductName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ProductName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupplierCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierSelect コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierSelect As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''SupplierInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierInfo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''R3SupplierCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents R3SupplierCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierCountry コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierContactPerson コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierContactPerson As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MakerCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MakerCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MakerSelect コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MakerSelect As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''MakerInfo コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MakerInfo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MakerName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MakerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MakerCountry コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MakerCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierItemName コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierItemName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PaymentTerm コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents PaymentTerm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_PaymentTerms コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_PaymentTerms As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ShippingHandlingCurrency コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ShippingHandlingCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_Currency コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_Currency As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ShippingHandlingFee コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ShippingHandlingFee As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Purpose コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Purpose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RequiredPurity コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RequiredPurity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RequiredQMMethod コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RequiredQMMethod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RequiredSpecification コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RequiredSpecification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SpecSheet コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SpecSheet As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Specification コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Specification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnqUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_EnqUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_EnqUser As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''EnqLocation コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuoUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_QuoUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_QuoUser As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''QuoLocation コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Comment コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Comment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnqQuantity_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqQuantity_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnqUnit_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqUnit_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnqPiece_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqPiece_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SDS_RFQUpdate_Qua コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_Qua As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Currency_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Currency_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UnitPrice_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UnitPrice_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoPer_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoPer_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoUnit_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoUnit_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_Unit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_Unit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''LeadTime_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LeadTime_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierItemNumber_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierItemNumber_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''POIssue_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POIssue_1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LineNumber1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LineNumber1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Incoterms_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Incoterms_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_Incoterms コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_Incoterms As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DeliveryTerm_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DeliveryTerm_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Purity_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Purity_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMMethod_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMMethod_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Packing_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Packing_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NoOfferReason_1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NoOfferReason_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_RFQUpdate_NoOffer コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SDS_RFQUpdate_NoOffer As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''EnqQuantity_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqQuantity_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnqUnit_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqUnit_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnqPiece_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqPiece_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Currency_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Currency_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UnitPrice_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UnitPrice_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoPer_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoPer_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoUnit_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoUnit_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LeadTime_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LeadTime_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierItemNumber_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierItemNumber_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''POIssue_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POIssue_2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LineNumber2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LineNumber2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Incoterms_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Incoterms_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DeliveryTerm_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DeliveryTerm_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Purity_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Purity_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMMethod_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMMethod_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Packing_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Packing_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NoOfferReason_2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NoOfferReason_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnqQuantity_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqQuantity_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnqUnit_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqUnit_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnqPiece_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqPiece_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Currency_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Currency_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UnitPrice_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UnitPrice_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoPer_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoPer_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoUnit_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoUnit_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LeadTime_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LeadTime_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierItemNumber_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierItemNumber_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''POIssue_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POIssue_3 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LineNumber3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LineNumber3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Incoterms_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Incoterms_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DeliveryTerm_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DeliveryTerm_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Purity_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Purity_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMMethod_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMMethod_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Packing_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Packing_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NoOfferReason_3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NoOfferReason_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnqQuantity_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqQuantity_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnqUnit_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqUnit_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnqPiece_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqPiece_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Currency_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Currency_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UnitPrice_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UnitPrice_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoPer_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoPer_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QuoUnit_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoUnit_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LeadTime_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LeadTime_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SupplierItemNumber_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SupplierItemNumber_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''POIssue_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents POIssue_4 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LineNumber4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LineNumber4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Incoterms_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Incoterms_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DeliveryTerm_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents DeliveryTerm_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Purity_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Purity_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''QMMethod_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QMMethod_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Packing_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Packing_4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NoOfferReason_4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NoOfferReason_4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RunMsg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RunMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFQStatus コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RFQStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Update コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Close コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Close As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''QuotedDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuotedDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdateDate コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdateDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''EnqLocationCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents EnqLocationCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QuoLocationCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents QuoLocationCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Hi_RFQStatusCode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Hi_RFQStatusCode As Global.System.Web.UI.WebControls.HiddenField
End Class
