Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' CodeExtension データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class CodeExtension


#Region "User-Defined Constant"

#End Region 'User-Defined Constant End

        Protected _CodeExtensionCode As String = String.Empty
        Protected _SortOrder As Integer = 0

        ''' <summary> 
        ''' CodeExtensionCode を設定、または取得する 
        ''' </summary> 
        Public Property CodeExtensionCode() As String
            Get
                Return _CodeExtensionCode
            End Get
            Set(ByVal value As String)
                _CodeExtensionCode = value
            End Set
        End Property

        ''' <summary> 
        ''' SortOrder を設定、または取得する 
        ''' </summary> 
        Public Property SortOrder() As Integer
            Get
                Return _SortOrder
            End Get
            Set(ByVal value As Integer)
                _SortOrder = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        ''' <param name="CodeExtensionCode">CodeExtensionCode</param>
        Public Sub Load(ByVal CodeExtensionCode As String)

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [CodeExtensionCode],")
            Value.AppendLine("    [SortOrder]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [CodeExtension]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [CodeExtensionCode] = @CodeExtensionCode")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.AddWithValue("CodeExtensionCode", CodeExtensionCode)
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("CodeExtensionCode"), _CodeExtensionCode)
                        SetProperty(DBReader("SortOrder"), _SortOrder)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        ''' <summary> 
        ''' データベースへデータを書き込む。
        ''' </summary> 
        ''' <returns>IDENTITY で自動的に挿入された ID 値。更新または IDENTITY 列が無い場合は 0 が返る。</returns> 
        Public Function Save() As Integer

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                DBConn.Open()
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    Dim i_Identity As Integer = Me.Save(DBCommand)
                    Return i_Identity
                End Using
            End Using

        End Function

        ''' <summary> 
        ''' データベースへデータを書き込む。(Facade 専用)
        ''' </summary> 
        ''' <param name="DBCommand">SqlCommand</param>
        ''' <returns>IDENTITY で自動的に挿入された ID 値。更新または IDENTITY 列が無い場合は 0 が返る。</returns> 
        Public Function Save(ByVal DBCommand As SqlCommand) As Integer

            Dim i_ID As Integer = 0
            DBCommand.CommandText = CreateSaveSQL()
            DBCommand.Parameters.Clear()
            DBCommand.Parameters.AddWithValue("CodeExtensionCode", _CodeExtensionCode)
            DBCommand.Parameters.AddWithValue("SortOrder", _SortOrder)
            Dim ob_ID As Object = DBCommand.ExecuteScalar()
            If Not IsDBNull(ob_ID) Then
                i_ID = CInt(ob_ID)
            End If
            Return i_ID

        End Function

        ''' <summary> 
        ''' データベースへデータを書き込む SQL 文字列を生成する。
        ''' </summary> 
        ''' <returns>生成した SQL 文字列</returns> 
        Private Function CreateSaveSQL() As String

            Dim Value As New StringBuilder()
            Value.AppendLine("IF(")
            Value.AppendLine("    SELECT")
            Value.AppendLine("        COUNT(*)")
            Value.AppendLine("    FROM")
            Value.AppendLine("        [CodeExtension]")
            Value.AppendLine("    WHERE")
            Value.AppendLine("        [CodeExtensionCode] = @CodeExtensionCode")
            Value.AppendLine("    ) = 0")
            Value.AppendLine("        INSERT [CodeExtension] (")
            Value.AppendLine("            [CodeExtensionCode],")
            Value.AppendLine("            [SortOrder]")
            Value.AppendLine("        )")
            Value.AppendLine("        Values(")
            Value.AppendLine("            @CodeExtensionCode,")
            Value.AppendLine("            @SortOrder")
            Value.AppendLine("        )")
            Value.AppendLine("    ELSE")
            Value.AppendLine("        UPDATE")
            Value.AppendLine("            [CodeExtension]")
            Value.AppendLine("        SET")
            Value.AppendLine("            [CodeExtensionCode] = @CodeExtensionCode,")
            Value.AppendLine("            [SortOrder] = @SortOrder")
            Value.AppendLine("        WHERE ")
            Value.AppendLine("            [CodeExtensionCode] = @CodeExtensionCode")
            Value.AppendLine(";")
            Value.AppendLine("SELECT SCOPE_IDENTITY();")
            Return Value.ToString()

        End Function

        ''' <summary> 
        ''' データの存在チェックを行う。
        ''' </summary> 
        ''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        ''' <param name="CodeExtensionCode">CodeExtensionCode</param>
        Public Shared Function IsExists(ByVal CodeExtensionCode As String) As Boolean

            ' データの存在チェックを行う SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    COUNT(*)")
            Value.AppendLine("FROM")
            Value.AppendLine("    [CodeExtension]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [CodeExtensionCode] = @CodeExtensionCode")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.Clear()
                    DBCommand.Parameters.AddWithValue("CodeExtensionCode", CodeExtensionCode)
                    DBConn.Open()
                    Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
                    Return i_Count > 0
                End Using
            End Using

        End Function

#Region "User-Defined Methods"

        ''' <summary>
        ''' CodeExtensionのプルダウンにCodeExtensionを設定する 
        ''' </summary>
        ''' <remarks></remarks>
        ''' <returns>DropDownListItems</returns>
        Public Shared Function GetCodeExtensionDropDownList(st_ProductNumber As String) As List(Of DropDownListItems)
            Dim dropDownListItems As List(Of DropDownListItems) = New List(Of DropDownListItems)

            Dim sb_SQL As StringBuilder = New StringBuilder

            sb_SQL.AppendLine("SELECT ")
            sb_SQL.AppendLine("	 CE.[CodeExtensionCode] AS ItemValue, ")
            sb_SQL.AppendLine("  CE.[SortOrder] AS ItemOrder ")
            sb_SQL.AppendLine("FROM ")
            sb_SQL.AppendLine("  [CodeExtension] AS CE ")
            If Not String.IsNullOrWhiteSpace(st_ProductNumber) Then 
                sb_SQL.AppendLine("  INNER JOIN [s_Material] AS M ")
                sb_SQL.AppendLine("    ON M.[ERPProductNumber] = @ProductNumber + CE.[CodeExtensionCode] ")
            End If
            sb_SQL.AppendLine("ORDER BY CE.[SortOrder] ")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = sb_SQL.ToString()
                    DBCommand.Parameters.Clear()
                    If Not String.IsNullOrWhiteSpace(st_ProductNumber) Then 
                        DBCommand.Parameters.AddWithValue("ProductNumber", st_ProductNumber)
                    End If
                    DBConn.Open()

                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()

                    if DBReader.HasRows Then 
                        While DBReader.Read
                            Dim dc_DropDownListItems As DropDownListItems = New DropDownListItems

                            DBCommon.SetProperty(DBReader("ItemValue"), dc_DropDownListItems.ItemValue)
                            DBCommon.SetProperty(DBReader("ItemOrder"), dc_DropDownListItems.ItemOrder)
                            dropDownListItems.Add(dc_DropDownListItems)

                        End While

                    'else
                    '    Dim dc_DropDownListItems As DropDownListItems = New DropDownListItems

                    '    DBCommon.SetProperty(String.Empty, dc_DropDownListItems.ItemValue)
                    '    DBCommon.SetProperty(String.Empty, dc_DropDownListItems.ItemText)
                    '    DBCommon.SetProperty(0, dc_DropDownListItems.ItemOrder)
                    '    dropDownListItems.Add(dc_DropDownListItems)

                    End If

                    DBConn.Close

                    Return dropDownListItems

                End Using
            End Using

        End Function

        '''' <summary>
        '''' データベースのデータを削除する
        '''' </summary>
        '''' <param name="CodeExtensionCode">CodeExtensionCode</param>
        'Public Sub Delete(ByVal CodeExtensionCode As String)

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        DBConn.Open()
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            Delete(DBCommand, CodeExtensionCode)
        '        End Using
        '    End Using

        'End Sub

        '''' <summary>
        '''' データベースのデータを削除する (Facade 専用)
        '''' </summary>
        '''' <param name="DBCommand">SqlCommand</param>
        '''' <param name="CodeExtensionCode">CodeExtensionCode</param>
        'Public Sub Delete(ByVal DBCommand As SqlCommand, _
        '                  ByVal CodeExtensionCode As String)

        '    'データベースのデータを削除する SQL 文字列を生成する
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("DELETE FROM [CodeExtension]")
        '    Value.AppendLine("WHERE")
        '    Value.AppendLine("    [CodeExtensionCode] = @CodeExtensionCode")

        '    DBCommand.CommandText = Value.ToString()
        '    DBCommand.Parameters.Clear()
        '    DBCommand.Parameters.AddWithValue("CodeExtensionCode", CodeExtensionCode)
        '    DBCommand.ExecuteNonQuery()

        'End Sub

#End Region 'User-Defined Methods End

    End Class

    ''' <summary> 
    ''' CodeExtension リストクラス 
    ''' </summary> 
    Public Class CodeExtensionList
        Inherits List(Of CodeExtension)

#Region "User-Defined Constant of List"

#End Region 'User-Defined Constant of List End

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub
#Region "User-Defined Methods of List"

        '''' <summary>
        '''' データベースから全てのデータを読み込む
        '''' </summary>
        'Public Sub Load()

        '    'データベースから全てのデータを読み込む SQL 文字列を生成する
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("SELECT")
        '    Value.AppendLine("    [CodeExtensionCode],")
        '    Value.AppendLine("    [Text],")
        '    Value.AppendLine("    [SortOrder]")
        '    Value.AppendLine("FROM")
        '    Value.AppendLine("    [CodeExtension]")

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            DBCommand.CommandText = Value.ToString()
        '            DBConn.Open()
        '            Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
        '            While DBReader.Read()
        '                Dim dc_CodeExtension As New CodeExtension()
        '                SetProperty(DBReader("CodeExtensionCode"), dc_CodeExtension.CodeExtensionCode)
        '                SetProperty(DBReader("Text"), dc_CodeExtension.Text)
        '                SetProperty(DBReader("SortOrder"), dc_CodeExtension.SortOrder)
        '                Me.Add(dc_CodeExtension)
        '            End While
        '            DBReader.Close()
        '        End Using
        '    End Using

        'End Sub

#End Region 'User-Defined Methods of List End

    End Class

End Namespace
