Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' Purpose データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class Purpose


#Region "User-Defined Constant"

#End Region 'User-Defined Constant End

        Protected _PurposeCode As String = String.Empty
        Protected _Text As String = String.Empty
        Protected _SortOrder As Integer = 0
        Protected _IsVisiable As Boolean = False

        ''' <summary> 
        ''' PurposeCode を設定、または取得する 
        ''' </summary> 
        Public Property PurposeCode() As String
            Get
                Return _PurposeCode
            End Get
            Set(ByVal value As String)
                _PurposeCode = value
            End Set
        End Property

        ''' <summary> 
        ''' Text を設定、または取得する 
        ''' </summary> 
        Public Property Text() As String
            Get
                Return _Text
            End Get
            Set(ByVal value As String)
                _Text = value
            End Set
        End Property

        ''' <summary> 
        ''' SortOrder を設定、または取得する 
        ''' </summary> 
        Public Property SortOrder() As Integer
            Get
                Return _SortOrder
            End Get
            Set(ByVal value As Integer)
                _SortOrder = value
            End Set
        End Property

        ''' <summary> 
        ''' IsVisiable を設定、または取得する 
        ''' </summary> 
        Public Property IsVisiable() As Boolean
            Get
                Return _IsVisiable
            End Get
            Set(ByVal value As Boolean)
                _IsVisiable = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        ''' <param name="PurposeCode">PurposeCode</param>
        Public Sub Load(ByVal PurposeCode As String)

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [PurposeCode],")
            Value.AppendLine("    [Text],")
            Value.AppendLine("    [SortOrder],")
            Value.AppendLine("    [IsVisiable]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [Purpose]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [PurposeCode] = @PurposeCode")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.AddWithValue("PurposeCode", PurposeCode)
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("PurposeCode"), _PurposeCode)
                        SetProperty(DBReader("Text"), _Text)
                        SetProperty(DBReader("SortOrder"), _SortOrder)
                        SetProperty(DBReader("IsVisiable"), _IsVisiable)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        ''' <summary> 
        ''' データベースへデータを書き込む。
        ''' </summary> 
        ''' <returns>IDENTITY で自動的に挿入された ID 値。更新または IDENTITY 列が無い場合は 0 が返る。</returns> 
        Public Function Save() As Integer

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                DBConn.Open()
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    Dim i_Identity As Integer = Me.Save(DBCommand)
                    Return i_Identity
                End Using
            End Using

        End Function

        ''' <summary> 
        ''' データベースへデータを書き込む。(Facade 専用)
        ''' </summary> 
        ''' <param name="DBCommand">SqlCommand</param>
        ''' <returns>IDENTITY で自動的に挿入された ID 値。更新または IDENTITY 列が無い場合は 0 が返る。</returns> 
        Public Function Save(ByVal DBCommand As SqlCommand) As Integer

            Dim i_ID As Integer = 0
            DBCommand.CommandText = CreateSaveSQL()
            DBCommand.Parameters.Clear()
            DBCommand.Parameters.AddWithValue("PurposeCode", _PurposeCode)
            DBCommand.Parameters.AddWithValue("Text", _Text)
            DBCommand.Parameters.AddWithValue("SortOrder", _SortOrder)
            DBCommand.Parameters.AddWithValue("IsVisiable", _IsVisiable)
            Dim ob_ID As Object = DBCommand.ExecuteScalar()
            If Not IsDBNull(ob_ID) Then
                i_ID = CInt(ob_ID)
            End If
            Return i_ID

        End Function

        ''' <summary> 
        ''' データベースへデータを書き込む SQL 文字列を生成する。
        ''' </summary> 
        ''' <returns>生成した SQL 文字列</returns> 
        Private Function CreateSaveSQL() As String

            Dim Value As New StringBuilder()
            Value.AppendLine("IF(")
            Value.AppendLine("    SELECT")
            Value.AppendLine("        COUNT(*)")
            Value.AppendLine("    FROM")
            Value.AppendLine("        [Purpose]")
            Value.AppendLine("    WHERE")
            Value.AppendLine("        [PurposeCode] = @PurposeCode")
            Value.AppendLine("    ) = 0")
            Value.AppendLine("        INSERT [Purpose] (")
            Value.AppendLine("            [PurposeCode],")
            Value.AppendLine("            [Text],")
            Value.AppendLine("            [SortOrder],")
            Value.AppendLine("            [IsVisiable]")
            Value.AppendLine("        )")
            Value.AppendLine("        Values(")
            Value.AppendLine("            @PurposeCode,")
            Value.AppendLine("            @Text,")
            Value.AppendLine("            @SortOrder,")
            Value.AppendLine("            @IsVisiable")
            Value.AppendLine("        )")
            Value.AppendLine("    ELSE")
            Value.AppendLine("        UPDATE")
            Value.AppendLine("            [Purpose]")
            Value.AppendLine("        SET")
            Value.AppendLine("            [PurposeCode] = @PurposeCode,")
            Value.AppendLine("            [Text] = @Text,")
            Value.AppendLine("            [SortOrder] = @SortOrder,")
            Value.AppendLine("            [IsVisiable] = @IsVisiable")
            Value.AppendLine("        WHERE ")
            Value.AppendLine("            [PurposeCode] = @PurposeCode")
            Value.AppendLine(";")
            Value.AppendLine("SELECT SCOPE_IDENTITY();")
            Return Value.ToString()

        End Function

        ''' <summary> 
        ''' データの存在チェックを行う。
        ''' </summary> 
        ''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        ''' <param name="PurposeCode">PurposeCode</param>
        Public Shared Function IsExists(ByVal PurposeCode As String) As Boolean

            ' データの存在チェックを行う SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    COUNT(*)")
            Value.AppendLine("FROM")
            Value.AppendLine("    [Purpose]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [PurposeCode] = @PurposeCode")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.Clear()
                    DBCommand.Parameters.AddWithValue("PurposeCode", PurposeCode)
                    DBConn.Open()
                    Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
                    Return i_Count > 0
                End Using
            End Using

        End Function

#Region "User-Defined Methods"

        '''' <summary>
        '''' データベースのデータを削除する
        '''' </summary>
        '''' <param name="PurposeCode">PurposeCode</param>
        'Public Sub Delete(ByVal PurposeCode As String)

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        DBConn.Open()
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            Delete(DBCommand, PurposeCode)
        '        End Using
        '    End Using

        'End Sub

        '''' <summary>
        '''' データベースのデータを削除する (Facade 専用)
        '''' </summary>
        '''' <param name="DBCommand">SqlCommand</param>
        '''' <param name="PurposeCode">PurposeCode</param>
        'Public Sub Delete(ByVal DBCommand As SqlCommand, _
        '                  ByVal PurposeCode As String)

        '    'データベースのデータを削除する SQL 文字列を生成する
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("DELETE FROM [Purpose]")
        '    Value.AppendLine("WHERE")
        '    Value.AppendLine("    [PurposeCode] = @PurposeCode")

        '    DBCommand.CommandText = Value.ToString()
        '    DBCommand.Parameters.Clear()
        '    DBCommand.Parameters.AddWithValue("PurposeCode", PurposeCode)
        '    DBCommand.ExecuteNonQuery()

        'End Sub

#End Region 'User-Defined Methods End

    End Class

    ''' <summary> 
    ''' Purpose リストクラス 
    ''' </summary> 
    Public Class PurposeList
        Inherits List(Of Purpose)

#Region "User-Defined Constant of List"

#End Region 'User-Defined Constant of List End

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub

#Region "User-Defined Methods of List"

        ''' <summary>
        ''' データベースから全てのデータを読み込む
        ''' </summary>
        Public Sub Load()

            'データベースから全てのデータを読み込む SQL 文字列を生成する
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [PurposeCode],")
            Value.AppendLine("    [Text],")
            Value.AppendLine("    [SortOrder]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [Purpose]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [IsVisiable] = 1")
            Value.AppendLine("ORDER BY")
            Value.AppendLine("    SortOrder")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        Dim dc_Purpose As New Purpose()
                        SetProperty(DBReader("PurposeCode"), dc_Purpose.PurposeCode)
                        SetProperty(DBReader("Text"), dc_Purpose.Text)
                        SetProperty(DBReader("SortOrder"), dc_Purpose.SortOrder)
                        Me.Add(dc_Purpose)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        ''' <summary>
        ''' Purposeドロップダウンリスト設定
        ''' </summary>
        ''' <param name="Combo">ドロップダウンリスト</param>
        ''' <remarks></remarks>
        Public Sub SetPurposeDropDownList(ByVal Combo As System.Web.UI.WebControls.ListControl)
            Combo.Items.Clear()
            Combo.Items.Add("All")
            Me.Load()

            For Each Purpose As Purpose In Me
                Combo.Items.Add(New ListItem(Purpose.Text, Purpose.Text))
            Next
        End Sub

#End Region 'User-Defined Methods of List End

    End Class

End Namespace
