Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' RFQHeader データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class RFQHeader


#Region "User-Defined Constant"

#End Region 'User-Defined Constant End

        Protected _RFQNumber As Integer = 0
        Protected _EnqLocationCode As String = String.Empty
        Protected _EnqUserID As Integer = 0
        Protected _QuoLocationCode As String = String.Empty
        Protected _QuoUserID As Integer? = Nothing
        Protected _ProductID As Integer = 0
        Protected _SupplierCode As Integer = 0
        Protected _MakerCode As Integer? = Nothing
        Protected _PurposeCode As String = String.Empty
        Protected _RequiredPurity As String = String.Empty
        Protected _RequiredQMMethod As String = String.Empty
        Protected _RequiredSpecification As String = String.Empty
        Protected _SpecSheet As Boolean = False
        Protected _Specification As String = String.Empty
        Protected _SupplierContactPerson As String = String.Empty
        Protected _SupplierItemName As String = String.Empty
        Protected _ShippingHandlingFee As Decimal? = Nothing
        Protected _ShippingHandlingCurrencyCode As String = String.Empty
        Protected _PaymentTermCode As String = String.Empty
        Protected _Comment As String = String.Empty
        Protected _QuotedDate As DateTime = New DateTime(0)
        Protected _RFQStatusCode As String = String.Empty
        Protected _Priority As String = String.Empty
        Protected _CreatedBy As Integer = 0
        Protected _CreateDate As DateTime = New DateTime(0)
        Protected _UpdatedBy As Integer = 0
        Protected _UpdateDate As DateTime = New DateTime(0)
        Protected _EnqStorageLocation As String = String.Empty
        Protected _QuoStorageLocation As String = String.Empty
        Protected _SupplierContactPersonSel As String = String.Empty
        Protected _SAPMakerCode As Integer? = Nothing
        Protected _SupplierOfferValidTo As String = String.Empty
        Protected _CodeExtensionCode As String = String.Empty

        ''' <summary> 
        ''' RFQNumber を設定、または取得する 
        ''' </summary> 
        Public Property RFQNumber() As Integer
            Get
                Return _RFQNumber
            End Get
            Set(ByVal value As Integer)
                _RFQNumber = value
            End Set
        End Property

        ''' <summary> 
        ''' EnqLocationCode を設定、または取得する 
        ''' </summary> 
        Public Property EnqLocationCode() As String
            Get
                Return _EnqLocationCode
            End Get
            Set(ByVal value As String)
                _EnqLocationCode = value
            End Set
        End Property

        ''' <summary> 
        ''' EnqUserID を設定、または取得する 
        ''' </summary> 
        Public Property EnqUserID() As Integer
            Get
                Return _EnqUserID
            End Get
            Set(ByVal value As Integer)
                _EnqUserID = value
            End Set
        End Property

        ''' <summary> 
        ''' QuoLocationCode を設定、または取得する 
        ''' </summary> 
        Public Property QuoLocationCode() As String
            Get
                Return _QuoLocationCode
            End Get
            Set(ByVal value As String)
                _QuoLocationCode = value
            End Set
        End Property

        ''' <summary> 
        ''' QuoUserID を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(QuoUserID.HasValue, QuoUserID, 0)
        '''     Dim val As Integer = QuoUserID.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property QuoUserID() As Integer?
            Get
                Return _QuoUserID
            End Get
            Set(ByVal value As Integer?)
                _QuoUserID = value
            End Set
        End Property

        ''' <summary> 
        ''' ProductID を設定、または取得する 
        ''' </summary> 
        Public Property ProductID() As Integer
            Get
                Return _ProductID
            End Get
            Set(ByVal value As Integer)
                _ProductID = value
            End Set
        End Property

        ''' <summary> 
        ''' SupplierCode を設定、または取得する 
        ''' </summary> 
        Public Property SupplierCode() As Integer
            Get
                Return _SupplierCode
            End Get
            Set(ByVal value As Integer)
                _SupplierCode = value
            End Set
        End Property

        ''' <summary> 
        ''' MakerCode を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(MakerCode.HasValue, MakerCode, 0)
        '''     Dim val As Integer = MakerCode.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property MakerCode() As Integer?
            Get
                Return _MakerCode
            End Get
            Set(ByVal value As Integer?)
                _MakerCode = value
            End Set
        End Property

        ''' <summary> 
        ''' PurposeCode を設定、または取得する 
        ''' </summary> 
        Public Property PurposeCode() As String
            Get
                Return _PurposeCode
            End Get
            Set(ByVal value As String)
                _PurposeCode = value
            End Set
        End Property

        ''' <summary> 
        ''' RequiredPurity を設定、または取得する 
        ''' </summary> 
        Public Property RequiredPurity() As String
            Get
                Return _RequiredPurity
            End Get
            Set(ByVal value As String)
                _RequiredPurity = value
            End Set
        End Property

        ''' <summary> 
        ''' RequiredQMMethod を設定、または取得する 
        ''' </summary> 
        Public Property RequiredQMMethod() As String
            Get
                Return _RequiredQMMethod
            End Get
            Set(ByVal value As String)
                _RequiredQMMethod = value
            End Set
        End Property

        ''' <summary> 
        ''' RequiredSpecification を設定、または取得する 
        ''' </summary> 
        Public Property RequiredSpecification() As String
            Get
                Return _RequiredSpecification
            End Get
            Set(ByVal value As String)
                _RequiredSpecification = value
            End Set
        End Property

        ''' <summary> 
        ''' SpecSheet を設定、または取得する 
        ''' </summary> 
        Public Property SpecSheet() As Boolean
            Get
                Return _SpecSheet
            End Get
            Set(ByVal value As Boolean)
                _SpecSheet = value
            End Set
        End Property

        ''' <summary> 
        ''' Specification を設定、または取得する 
        ''' </summary> 
        Public Property Specification() As String
            Get
                Return _Specification
            End Get
            Set(ByVal value As String)
                _Specification = value
            End Set
        End Property

        ''' <summary> 
        ''' SupplierContactPerson を設定、または取得する 
        ''' </summary> 
        Public Property SupplierContactPerson() As String
            Get
                Return _SupplierContactPerson
            End Get
            Set(ByVal value As String)
                _SupplierContactPerson = value
            End Set
        End Property

        ''' <summary> 
        ''' SupplierItemName を設定、または取得する 
        ''' </summary> 
        Public Property SupplierItemName() As String
            Get
                Return _SupplierItemName
            End Get
            Set(ByVal value As String)
                _SupplierItemName = value
            End Set
        End Property

        ''' <summary> 
        ''' ShippingHandlingFee を設定、または取得する 
        ''' <para>
        ''' ※ Decimal 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Decimal = IIf(ShippingHandlingFee.HasValue, ShippingHandlingFee, 0)
        '''     Dim val As Decimal = ShippingHandlingFee.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property ShippingHandlingFee() As Decimal?
            Get
                Return _ShippingHandlingFee
            End Get
            Set(ByVal value As Decimal?)
                _ShippingHandlingFee = value
            End Set
        End Property

        ''' <summary> 
        ''' ShippingHandlingCurrencyCode を設定、または取得する 
        ''' </summary> 
        Public Property ShippingHandlingCurrencyCode() As String
            Get
                Return _ShippingHandlingCurrencyCode
            End Get
            Set(ByVal value As String)
                _ShippingHandlingCurrencyCode = value
            End Set
        End Property

        ''' <summary> 
        ''' PaymentTermCode を設定、または取得する 
        ''' </summary> 
        Public Property PaymentTermCode() As String
            Get
                Return _PaymentTermCode
            End Get
            Set(ByVal value As String)
                _PaymentTermCode = value
            End Set
        End Property

        ''' <summary> 
        ''' Comment を設定、または取得する 
        ''' </summary> 
        Public Property Comment() As String
            Get
                Return _Comment
            End Get
            Set(ByVal value As String)
                _Comment = value
            End Set
        End Property

        ''' <summary> 
        ''' QuotedDate を設定、または取得する 
        ''' </summary> 
        Public Property QuotedDate() As DateTime
            Get
                Return _QuotedDate
            End Get
            Set(ByVal value As DateTime)
                _QuotedDate = value
            End Set
        End Property

        ''' <summary> 
        ''' RFQStatusCode を設定、または取得する 
        ''' </summary> 
        Public Property RFQStatusCode() As String
            Get
                Return _RFQStatusCode
            End Get
            Set(ByVal value As String)
                _RFQStatusCode = value
            End Set
        End Property

        ''' <summary> 
        ''' Priority を設定、または取得する 
        ''' </summary> 
        Public Property Priority() As String
            Get
                Return _Priority
            End Get
            Set(ByVal value As String)
                _Priority = value
            End Set
        End Property

        ''' <summary> 
        ''' CreatedBy を設定、または取得する 
        ''' </summary> 
        Public Property CreatedBy() As Integer
            Get
                Return _CreatedBy
            End Get
            Set(ByVal value As Integer)
                _CreatedBy = value
            End Set
        End Property

        ''' <summary> 
        ''' CreateDate を設定、または取得する 
        ''' </summary> 
        Public Property CreateDate() As DateTime
            Get
                Return _CreateDate
            End Get
            Set(ByVal value As DateTime)
                _CreateDate = value
            End Set
        End Property

        ''' <summary> 
        ''' UpdatedBy を設定、または取得する 
        ''' </summary> 
        Public Property UpdatedBy() As Integer
            Get
                Return _UpdatedBy
            End Get
            Set(ByVal value As Integer)
                _UpdatedBy = value
            End Set
        End Property

        ''' <summary> 
        ''' UpdateDate を設定、または取得する 
        ''' </summary> 
        Public Property UpdateDate() As DateTime
            Get
                Return _UpdateDate
            End Get
            Set(ByVal value As DateTime)
                _UpdateDate = value
            End Set
        End Property

        ''' <summary> 
        ''' EnqStorageLocation を設定、または取得する 
        ''' </summary> 
        Public Property EnqStorageLocation() As String
            Get
                Return _EnqStorageLocation
            End Get
            Set(ByVal value As String)
                _EnqStorageLocation = value
            End Set
        End Property

        ''' <summary> 
        ''' QuoStorageLocation を設定、または取得する 
        ''' </summary> 
        Public Property QuoStorageLocation() As String
            Get
                Return _QuoStorageLocation
            End Get
            Set(ByVal value As String)
                _QuoStorageLocation = value
            End Set
        End Property

        ''' <summary> 
        ''' SupplierContactPersonSel を設定、または取得する 
        ''' </summary> 
        Public Property SupplierContactPersonSel() As String
            Get
                Return _SupplierContactPersonSel
            End Get
            Set(ByVal value As String)
                _SupplierContactPersonSel = value
            End Set
        End Property

        ''' <summary> 
        ''' SAPMakerCode を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(SAPMakerCode.HasValue, SAPMakerCode, 0)
        '''     Dim val As Integer = SAPMakerCode.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property SAPMakerCode() As Integer?
            Get
                Return _SAPMakerCode
            End Get
            Set(ByVal value As Integer?)
                _SAPMakerCode = value
            End Set
        End Property

        ''' <summary> 
        ''' SupplierOfferValidTo を設定、または取得する 
        ''' </summary> 
        Public Property SupplierOfferValidTo() As String
            Get
                Return _SupplierOfferValidTo
            End Get
            Set(ByVal value As String)
                _SupplierOfferValidTo = value
            End Set
        End Property

        ''' <summary> 
        ''' CodeExtensionCode を設定、または取得する 
        ''' </summary> 
        Public Property CodeExtensionCode() As String
            Get
                Return _CodeExtensionCode
            End Get
            Set(ByVal value As String)
                _CodeExtensionCode = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        ''' <param name="RFQNumber">RFQNumber</param>
        Public Sub Load(ByVal RFQNumber As Integer)

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [RFQNumber],")
            Value.AppendLine("    [EnqLocationCode],")
            Value.AppendLine("    [EnqUserID],")
            Value.AppendLine("    [QuoLocationCode],")
            Value.AppendLine("    [QuoUserID],")
            Value.AppendLine("    [ProductID],")
            Value.AppendLine("    [SupplierCode],")
            Value.AppendLine("    [MakerCode],")
            Value.AppendLine("    [PurposeCode],")
            Value.AppendLine("    [RequiredPurity],")
            Value.AppendLine("    [RequiredQMMethod],")
            Value.AppendLine("    [RequiredSpecification],")
            Value.AppendLine("    [SpecSheet],")
            Value.AppendLine("    [Specification],")
            Value.AppendLine("    [SupplierContactPerson],")
            Value.AppendLine("    [SupplierItemName],")
            Value.AppendLine("    [ShippingHandlingFee],")
            Value.AppendLine("    [ShippingHandlingCurrencyCode],")
            Value.AppendLine("    [PaymentTermCode],")
            Value.AppendLine("    [Comment],")
            Value.AppendLine("    [QuotedDate],")
            Value.AppendLine("    [RFQStatusCode],")
            Value.AppendLine("    [Priority],")
            Value.AppendLine("    [CreatedBy],")
            Value.AppendLine("    [CreateDate],")
            Value.AppendLine("    [UpdatedBy],")
            Value.AppendLine("    [UpdateDate],")
            Value.AppendLine("    [EnqStorageLocation],")
            Value.AppendLine("    [QuoStorageLocation],")
            Value.AppendLine("    [SupplierContactPersonSel],")
            Value.AppendLine("    [SAPMakerCode],")
            Value.AppendLine("    [SupplierOfferValidTo],")
            Value.AppendLine("    [CodeExtensionCode]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [RFQHeader]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [RFQNumber] = @RFQNumber")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.AddWithValue("RFQNumber", RFQNumber)
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("RFQNumber"), _RFQNumber)
                        SetProperty(DBReader("EnqLocationCode"), _EnqLocationCode)
                        SetProperty(DBReader("EnqUserID"), _EnqUserID)
                        SetProperty(DBReader("QuoLocationCode"), _QuoLocationCode)
                        SetProperty(DBReader("QuoUserID"), _QuoUserID)
                        SetProperty(DBReader("ProductID"), _ProductID)
                        SetProperty(DBReader("SupplierCode"), _SupplierCode)
                        SetProperty(DBReader("MakerCode"), _MakerCode)
                        SetProperty(DBReader("PurposeCode"), _PurposeCode)
                        SetProperty(DBReader("RequiredPurity"), _RequiredPurity)
                        SetProperty(DBReader("RequiredQMMethod"), _RequiredQMMethod)
                        SetProperty(DBReader("RequiredSpecification"), _RequiredSpecification)
                        SetProperty(DBReader("SpecSheet"), _SpecSheet)
                        SetProperty(DBReader("Specification"), _Specification)
                        SetProperty(DBReader("SupplierContactPerson"), _SupplierContactPerson)
                        SetProperty(DBReader("SupplierItemName"), _SupplierItemName)
                        SetProperty(DBReader("ShippingHandlingFee"), _ShippingHandlingFee)
                        SetProperty(DBReader("ShippingHandlingCurrencyCode"), _ShippingHandlingCurrencyCode)
                        SetProperty(DBReader("PaymentTermCode"), _PaymentTermCode)
                        SetProperty(DBReader("Comment"), _Comment)
                        SetProperty(DBReader("QuotedDate"), _QuotedDate)
                        SetProperty(DBReader("RFQStatusCode"), _RFQStatusCode)
                        SetProperty(DBReader("Priority"), _Priority)
                        SetProperty(DBReader("CreatedBy"), _CreatedBy)
                        SetProperty(DBReader("CreateDate"), _CreateDate)
                        SetProperty(DBReader("UpdatedBy"), _UpdatedBy)
                        SetProperty(DBReader("UpdateDate"), _UpdateDate)
                        SetProperty(DBReader("EnqStorageLocation"), _EnqStorageLocation)
                        SetProperty(DBReader("QuoStorageLocation"), _QuoStorageLocation)
                        SetProperty(DBReader("SupplierContactPersonSel"), _SupplierContactPersonSel)
                        SetProperty(DBReader("SAPMakerCode"), _SAPMakerCode)
                        SetProperty(DBReader("SupplierOfferValidTo"), _SupplierOfferValidTo)
                        SetProperty(DBReader("CodeExtensionCode"), _CodeExtensionCode)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        ''' <summary> 
        ''' データベースへデータを書き込む。
        ''' </summary> 
        ''' <returns>IDENTITY で自動的に挿入された ID 値。更新または IDENTITY 列が無い場合は 0 が返る。</returns> 
        Public Function Save() As Integer

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                DBConn.Open()
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    Dim i_Identity As Integer = Me.Save(DBCommand)
                    Return i_Identity
                End Using
            End Using

        End Function

        ''' <summary> 
        ''' データベースへデータを書き込む。(Facade 専用)
        ''' </summary> 
        ''' <param name="DBCommand">SqlCommand</param>
        ''' <returns>IDENTITY で自動的に挿入された ID 値。更新または IDENTITY 列が無い場合は 0 が返る。</returns> 
        Public Function Save(ByVal DBCommand As SqlCommand) As Integer

            Dim i_ID As Integer = 0
            DBCommand.CommandText = CreateSaveSQL()
            DBCommand.Parameters.Clear()
            DBCommand.Parameters.AddWithValue("RFQNumber", _RFQNumber)
            DBCommand.Parameters.AddWithValue("EnqLocationCode", _EnqLocationCode)
            DBCommand.Parameters.AddWithValue("EnqUserID", _EnqUserID)
            DBCommand.Parameters.AddWithValue("QuoLocationCode", ConvertEmptyStringToNull(_QuoLocationCode))
            DBCommand.Parameters.AddWithValue("QuoUserID", ConvertNothingToNull(_QuoUserID))
            DBCommand.Parameters.AddWithValue("ProductID", _ProductID)
            DBCommand.Parameters.AddWithValue("SupplierCode", _SupplierCode)
            DBCommand.Parameters.AddWithValue("MakerCode", ConvertNothingToNull(_MakerCode))
            DBCommand.Parameters.AddWithValue("PurposeCode", ConvertEmptyStringToNull(_PurposeCode))
            DBCommand.Parameters.AddWithValue("RequiredPurity", ConvertEmptyStringToNull(_RequiredPurity))
            DBCommand.Parameters.AddWithValue("RequiredQMMethod", ConvertEmptyStringToNull(_RequiredQMMethod))
            DBCommand.Parameters.AddWithValue("RequiredSpecification", ConvertEmptyStringToNull(_RequiredSpecification))
            DBCommand.Parameters.AddWithValue("SpecSheet", _SpecSheet)
            DBCommand.Parameters.AddWithValue("Specification", ConvertEmptyStringToNull(_Specification))
            DBCommand.Parameters.AddWithValue("SupplierContactPerson", ConvertEmptyStringToNull(_SupplierContactPerson))
            DBCommand.Parameters.AddWithValue("SupplierItemName", ConvertEmptyStringToNull(_SupplierItemName))
            DBCommand.Parameters.AddWithValue("ShippingHandlingFee", ConvertNothingToNull(_ShippingHandlingFee))
            DBCommand.Parameters.AddWithValue("ShippingHandlingCurrencyCode", ConvertEmptyStringToNull(_ShippingHandlingCurrencyCode))
            DBCommand.Parameters.AddWithValue("PaymentTermCode", ConvertEmptyStringToNull(_PaymentTermCode))
            DBCommand.Parameters.AddWithValue("Comment", ConvertEmptyStringToNull(_Comment))
            DBCommand.Parameters.AddWithValue("QuotedDate", ConvertDefaultDateTimeToNull(_QuotedDate))
            DBCommand.Parameters.AddWithValue("RFQStatusCode", _RFQStatusCode)
            DBCommand.Parameters.AddWithValue("Priority", ConvertEmptyStringToNull(_Priority))
            DBCommand.Parameters.AddWithValue("CreatedBy", _CreatedBy)
            DBCommand.Parameters.AddWithValue("UpdatedBy", _UpdatedBy)
            DBCommand.Parameters.AddWithValue("EnqStorageLocation", ConvertEmptyStringToNull(_EnqStorageLocation))
            DBCommand.Parameters.AddWithValue("QuoStorageLocation", ConvertEmptyStringToNull(_QuoStorageLocation))
            DBCommand.Parameters.AddWithValue("SupplierContactPersonSel", ConvertEmptyStringToNull(_SupplierContactPersonSel))
            DBCommand.Parameters.AddWithValue("SAPMakerCode", ConvertNothingToNull(_SAPMakerCode))
            DBCommand.Parameters.AddWithValue("SupplierOfferValidTo", ConvertEmptyStringToNull(_SupplierOfferValidTo))
            DBCommand.Parameters.AddWithValue("CodeExtensionCode", ConvertEmptyStringToNull(_CodeExtensionCode))
            Dim ob_ID As Object = DBCommand.ExecuteScalar()
            If Not IsDBNull(ob_ID) Then
                i_ID = CInt(ob_ID)
            End If
            Return i_ID

        End Function

        ''' <summary> 
        ''' データベースへデータを書き込む SQL 文字列を生成する。
        ''' </summary> 
        ''' <returns>生成した SQL 文字列</returns> 
        Private Function CreateSaveSQL() As String

            Dim Value As New StringBuilder()
            Value.AppendLine("IF(")
            Value.AppendLine("    SELECT")
            Value.AppendLine("        COUNT(*)")
            Value.AppendLine("    FROM")
            Value.AppendLine("        [RFQHeader]")
            Value.AppendLine("    WHERE")
            Value.AppendLine("        [RFQNumber] = @RFQNumber")
            Value.AppendLine("    ) = 0")
            Value.AppendLine("        INSERT [RFQHeader] (")
            Value.AppendLine("            [EnqLocationCode],")
            Value.AppendLine("            [EnqUserID],")
            Value.AppendLine("            [QuoLocationCode],")
            Value.AppendLine("            [QuoUserID],")
            Value.AppendLine("            [ProductID],")
            Value.AppendLine("            [SupplierCode],")
            Value.AppendLine("            [MakerCode],")
            Value.AppendLine("            [PurposeCode],")
            Value.AppendLine("            [RequiredPurity],")
            Value.AppendLine("            [RequiredQMMethod],")
            Value.AppendLine("            [RequiredSpecification],")
            Value.AppendLine("            [SpecSheet],")
            Value.AppendLine("            [Specification],")
            Value.AppendLine("            [SupplierContactPerson],")
            Value.AppendLine("            [SupplierItemName],")
            Value.AppendLine("            [ShippingHandlingFee],")
            Value.AppendLine("            [ShippingHandlingCurrencyCode],")
            Value.AppendLine("            [PaymentTermCode],")
            Value.AppendLine("            [Comment],")
            Value.AppendLine("            [QuotedDate],")
            Value.AppendLine("            [RFQStatusCode],")
            Value.AppendLine("            [Priority],")
            Value.AppendLine("            [CreatedBy],")
            Value.AppendLine("            [CreateDate],")
            Value.AppendLine("            [UpdatedBy],")
            Value.AppendLine("            [UpdateDate],")
            Value.AppendLine("            [EnqStorageLocation],")
            Value.AppendLine("            [QuoStorageLocation],")
            Value.AppendLine("            [SupplierContactPersonSel],")
            Value.AppendLine("            [SAPMakerCode],")
            Value.AppendLine("            [SupplierOfferValidTo],")
            Value.AppendLine("            [CodeExtensionCode]")
            Value.AppendLine("        )")
            Value.AppendLine("        Values(")
            Value.AppendLine("            @EnqLocationCode,")
            Value.AppendLine("            @EnqUserID,")
            Value.AppendLine("            @QuoLocationCode,")
            Value.AppendLine("            @QuoUserID,")
            Value.AppendLine("            @ProductID,")
            Value.AppendLine("            @SupplierCode,")
            Value.AppendLine("            @MakerCode,")
            Value.AppendLine("            @PurposeCode,")
            Value.AppendLine("            @RequiredPurity,")
            Value.AppendLine("            @RequiredQMMethod,")
            Value.AppendLine("            @RequiredSpecification,")
            Value.AppendLine("            @SpecSheet,")
            Value.AppendLine("            @Specification,")
            Value.AppendLine("            @SupplierContactPerson,")
            Value.AppendLine("            @SupplierItemName,")
            Value.AppendLine("            @ShippingHandlingFee,")
            Value.AppendLine("            @ShippingHandlingCurrencyCode,")
            Value.AppendLine("            @PaymentTermCode,")
            Value.AppendLine("            @Comment,")
            Value.AppendLine("            @QuotedDate,")
            Value.AppendLine("            @RFQStatusCode,")
            Value.AppendLine("            @Priority,")
            Value.AppendLine("            @CreatedBy,")
            Value.AppendLine("            GETDATE(),")
            Value.AppendLine("            @UpdatedBy,")
            Value.AppendLine("            GETDATE(),")
            Value.AppendLine("            @EnqStorageLocation,")
            Value.AppendLine("            @QuoStorageLocation,")
            Value.AppendLine("            @SupplierContactPersonSel,")
            Value.AppendLine("            @SAPMakerCode,")
            Value.AppendLine("            @SupplierOfferValidTo,")
            Value.AppendLine("            @CodeExtensionCode")
            Value.AppendLine("        )")
            Value.AppendLine("    ELSE")
            Value.AppendLine("        UPDATE")
            Value.AppendLine("            [RFQHeader]")
            Value.AppendLine("        SET")
            Value.AppendLine("            [EnqLocationCode] = @EnqLocationCode,")
            Value.AppendLine("            [EnqUserID] = @EnqUserID,")
            Value.AppendLine("            [QuoLocationCode] = @QuoLocationCode,")
            Value.AppendLine("            [QuoUserID] = @QuoUserID,")
            Value.AppendLine("            [ProductID] = @ProductID,")
            Value.AppendLine("            [SupplierCode] = @SupplierCode,")
            Value.AppendLine("            [MakerCode] = @MakerCode,")
            Value.AppendLine("            [PurposeCode] = @PurposeCode,")
            Value.AppendLine("            [RequiredPurity] = @RequiredPurity,")
            Value.AppendLine("            [RequiredQMMethod] = @RequiredQMMethod,")
            Value.AppendLine("            [RequiredSpecification] = @RequiredSpecification,")
            Value.AppendLine("            [SpecSheet] = @SpecSheet,")
            Value.AppendLine("            [Specification] = @Specification,")
            Value.AppendLine("            [SupplierContactPerson] = @SupplierContactPerson,")
            Value.AppendLine("            [SupplierItemName] = @SupplierItemName,")
            Value.AppendLine("            [ShippingHandlingFee] = @ShippingHandlingFee,")
            Value.AppendLine("            [ShippingHandlingCurrencyCode] = @ShippingHandlingCurrencyCode,")
            Value.AppendLine("            [PaymentTermCode] = @PaymentTermCode,")
            Value.AppendLine("            [Comment] = @Comment,")
            Value.AppendLine("            [QuotedDate] = @QuotedDate,")
            Value.AppendLine("            [RFQStatusCode] = @RFQStatusCode,")
            Value.AppendLine("            [Priority] = @Priority,")
            Value.AppendLine("            [UpdatedBy] = @UpdatedBy,")
            Value.AppendLine("            [UpdateDate] = GETDATE(),")
            Value.AppendLine("            [EnqStorageLocation] = @EnqStorageLocation,")
            Value.AppendLine("            [QuoStorageLocation] = @QuoStorageLocation,")
            Value.AppendLine("            [SupplierContactPersonSel] = @SupplierContactPersonSel,")
            Value.AppendLine("            [SAPMakerCode] = @SAPMakerCode,")
            Value.AppendLine("            [SupplierOfferValidTo] = @SupplierOfferValidTo,")
            Value.AppendLine("            [CodeExtensionCode] = @CodeExtensionCode")
            Value.AppendLine("        WHERE ")
            Value.AppendLine("            [RFQNumber] = @RFQNumber")
            Value.AppendLine(";")
            Value.AppendLine("SELECT SCOPE_IDENTITY();")
            Return Value.ToString()

        End Function

        ''' <summary> 
        ''' データの存在チェックを行う。
        ''' </summary> 
        ''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        ''' <param name="RFQNumber">RFQNumber</param>
        Public Shared Function IsExists(ByVal RFQNumber As Integer) As Boolean

            ' データの存在チェックを行う SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    COUNT(*)")
            Value.AppendLine("FROM")
            Value.AppendLine("    [RFQHeader]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [RFQNumber] = @RFQNumber")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.Clear()
                    DBCommand.Parameters.AddWithValue("RFQNumber", RFQNumber)
                    DBConn.Open()
                    Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
                    Return i_Count > 0
                End Using
            End Using

        End Function

#Region "User-Defined Methods"

        '''' <summary>
        '''' データベースのデータを削除する
        '''' </summary>
        '''' <param name="RFQNumber">RFQNumber</param>
        'Public Sub Delete(ByVal RFQNumber As Integer)

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        DBConn.Open()
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            Delete(DBCommand, RFQNumber)
        '        End Using
        '    End Using

        'End Sub

        '''' <summary>
        '''' データベースのデータを削除する (Facade 専用)
        '''' </summary>
        '''' <param name="DBCommand">SqlCommand</param>
        '''' <param name="RFQNumber">RFQNumber</param>
        'Public Sub Delete(ByVal DBCommand As SqlCommand, _
        '                  ByVal RFQNumber As Integer)

        '    'データベースのデータを削除する SQL 文字列を生成する
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("DELETE FROM [RFQHeader]")
        '    Value.AppendLine("WHERE")
        '    Value.AppendLine("    [RFQNumber] = @RFQNumber")

        '    DBCommand.CommandText = Value.ToString()
        '    DBCommand.Parameters.Clear()
        '    DBCommand.Parameters.AddWithValue("RFQNumber", RFQNumber)
        '    DBCommand.ExecuteNonQuery()

        'End Sub

#End Region 'User-Defined Methods End

    End Class

    ''' <summary> 
    ''' RFQHeader リストクラス 
    ''' </summary> 
    Public Class RFQHeaderList
        Inherits List(Of RFQHeader)

#Region "User-Defined Constant of List"

#End Region 'User-Defined Constant of List End

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub

#Region "User-Defined Methods of List"

        '''' <summary>
        '''' データベースから全てのデータを読み込む
        '''' </summary>
        'Public Sub Load()

        '    'データベースから全てのデータを読み込む SQL 文字列を生成する
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("SELECT")
        '    Value.AppendLine("    [RFQNumber],")
        '    Value.AppendLine("    [EnqLocationCode],")
        '    Value.AppendLine("    [EnqUserID],")
        '    Value.AppendLine("    [QuoLocationCode],")
        '    Value.AppendLine("    [QuoUserID],")
        '    Value.AppendLine("    [ProductID],")
        '    Value.AppendLine("    [SupplierCode],")
        '    Value.AppendLine("    [MakerCode],")
        '    Value.AppendLine("    [PurposeCode],")
        '    Value.AppendLine("    [RequiredPurity],")
        '    Value.AppendLine("    [RequiredQMMethod],")
        '    Value.AppendLine("    [RequiredSpecification],")
        '    Value.AppendLine("    [SpecSheet],")
        '    Value.AppendLine("    [Specification],")
        '    Value.AppendLine("    [SupplierContactPerson],")
        '    Value.AppendLine("    [SupplierItemName],")
        '    Value.AppendLine("    [ShippingHandlingFee],")
        '    Value.AppendLine("    [ShippingHandlingCurrencyCode],")
        '    Value.AppendLine("    [PaymentTermCode],")
        '    Value.AppendLine("    [Comment],")
        '    Value.AppendLine("    [QuotedDate],")
        '    Value.AppendLine("    [RFQStatusCode],")
        '    Value.AppendLine("    [Priority],")
        '    Value.AppendLine("    [CreatedBy],")
        '    Value.AppendLine("    [CreateDate],")
        '    Value.AppendLine("    [UpdatedBy],")
        '    Value.AppendLine("    [UpdateDate],")
        '    Value.AppendLine("    [EnqStorageLocation],")
        '    Value.AppendLine("    [QuoStorageLocation],")
        '    Value.AppendLine("    [SupplierContactPersonSel],")
        '    Value.AppendLine("    [SAPMakerCode],")
        '    Value.AppendLine("    [SupplierOfferValidTo],")
        '    Value.AppendLine("    [CodeExtensionCode]")
        '    Value.AppendLine("FROM")
        '    Value.AppendLine("    [RFQHeader]")

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            DBCommand.CommandText = Value.ToString()
        '            DBConn.Open()
        '            Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
        '            While DBReader.Read()
        '                Dim dc_RFQHeader As New RFQHeader()
        '                SetProperty(DBReader("RFQNumber"), dc_RFQHeader.RFQNumber)
        '                SetProperty(DBReader("EnqLocationCode"), dc_RFQHeader.EnqLocationCode)
        '                SetProperty(DBReader("EnqUserID"), dc_RFQHeader.EnqUserID)
        '                SetProperty(DBReader("QuoLocationCode"), dc_RFQHeader.QuoLocationCode)
        '                SetProperty(DBReader("QuoUserID"), dc_RFQHeader.QuoUserID)
        '                SetProperty(DBReader("ProductID"), dc_RFQHeader.ProductID)
        '                SetProperty(DBReader("SupplierCode"), dc_RFQHeader.SupplierCode)
        '                SetProperty(DBReader("MakerCode"), dc_RFQHeader.MakerCode)
        '                SetProperty(DBReader("PurposeCode"), dc_RFQHeader.PurposeCode)
        '                SetProperty(DBReader("RequiredPurity"), dc_RFQHeader.RequiredPurity)
        '                SetProperty(DBReader("RequiredQMMethod"), dc_RFQHeader.RequiredQMMethod)
        '                SetProperty(DBReader("RequiredSpecification"), dc_RFQHeader.RequiredSpecification)
        '                SetProperty(DBReader("SpecSheet"), dc_RFQHeader.SpecSheet)
        '                SetProperty(DBReader("Specification"), dc_RFQHeader.Specification)
        '                SetProperty(DBReader("SupplierContactPerson"), dc_RFQHeader.SupplierContactPerson)
        '                SetProperty(DBReader("SupplierItemName"), dc_RFQHeader.SupplierItemName)
        '                SetProperty(DBReader("ShippingHandlingFee"), dc_RFQHeader.ShippingHandlingFee)
        '                SetProperty(DBReader("ShippingHandlingCurrencyCode"), dc_RFQHeader.ShippingHandlingCurrencyCode)
        '                SetProperty(DBReader("PaymentTermCode"), dc_RFQHeader.PaymentTermCode)
        '                SetProperty(DBReader("Comment"), dc_RFQHeader.Comment)
        '                SetProperty(DBReader("QuotedDate"), dc_RFQHeader.QuotedDate)
        '                SetProperty(DBReader("RFQStatusCode"), dc_RFQHeader.RFQStatusCode)
        '                SetProperty(DBReader("Priority"), dc_RFQHeader.Priority)
        '                SetProperty(DBReader("CreatedBy"), dc_RFQHeader.CreatedBy)
        '                SetProperty(DBReader("CreateDate"), dc_RFQHeader.CreateDate)
        '                SetProperty(DBReader("UpdatedBy"), dc_RFQHeader.UpdatedBy)
        '                SetProperty(DBReader("UpdateDate"), dc_RFQHeader.UpdateDate)
        '                SetProperty(DBReader("EnqStorageLocation"), dc_RFQHeader.EnqStorageLocation)
        '                SetProperty(DBReader("QuoStorageLocation"), dc_RFQHeader.QuoStorageLocation)
        '                SetProperty(DBReader("SupplierContactPersonSel"), dc_RFQHeader.SupplierContactPersonSel)
        '                SetProperty(DBReader("SAPMakerCode"), dc_RFQHeader.SAPMakerCode)
        '                SetProperty(DBReader("SupplierOfferValidTo"), dc_RFQHeader.SupplierOfferValidTo)
        '                SetProperty(DBReader("CodeExtensionCode"), dc_RFQHeader.CodeExtensionCode)
        '                Me.Add(dc_RFQHeader)
        '            End While
        '            DBReader.Close()
        '        End Using
        '    End Using

        'End Sub

#End Region 'User-Defined Methods of List End

    End Class

End Namespace
