Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' s_BranchSortOrder データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class s_BranchSortOrder


        Protected _LocationCode As String = String.Empty
        Protected _DisplayLocationCode As String = String.Empty
        Protected _SortOrder As Integer? = Nothing

        ''' <summary> 
        ''' LocationCode を設定、または取得する 
        ''' </summary> 
        Public Property LocationCode() As String
            Get
                Return _LocationCode
            End Get
            Set(ByVal value As String)
                _LocationCode = value
            End Set
        End Property

        ''' <summary> 
        ''' DisplayLocationCode を設定、または取得する 
        ''' </summary> 
        Public Property DisplayLocationCode() As String
            Get
                Return _DisplayLocationCode
            End Get
            Set(ByVal value As String)
                _DisplayLocationCode = value
            End Set
        End Property

        ''' <summary> 
        ''' SortOrder を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(SortOrder.HasValue, SortOrder, 0)
        '''     Dim val As Integer = SortOrder.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property SortOrder() As Integer?
            Get
                Return _SortOrder
            End Get
            Set(ByVal value As Integer?)
                _SortOrder = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        Public Sub Load()

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [LocationCode],")
            Value.AppendLine("    [DisplayLocationCode],")
            Value.AppendLine("    [SortOrder]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_BranchSortOrder]")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("LocationCode"), _LocationCode)
                        SetProperty(DBReader("DisplayLocationCode"), _DisplayLocationCode)
                        SetProperty(DBReader("SortOrder"), _SortOrder)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        '''' <summary> 
        '''' データの存在チェックを行う。
        '''' </summary> 
        '''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        'Public Shared Function IsExists() As Boolean

        '    ' データの存在チェックを行う SQL 文字列を生成する。
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("SELECT")
        '    Value.AppendLine("    COUNT(*)")
        '    Value.AppendLine("FROM")
        '    Value.AppendLine("    [s_BranchSortOrder]")

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            DBCommand.CommandText = Value.ToString()
        '            DBCommand.Parameters.Clear()
        '            DBConn.Open()
        '            Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
        '            Return i_Count > 0
        '        End Using
        '    End Using

        'End Function

    End Class

    ''' <summary> 
    ''' s_BranchSortOrder リストクラス 
    ''' </summary> 
    Public Class s_BranchSortOrderList
        Inherits List(Of s_BranchSortOrder)

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub

    End Class

End Namespace
