Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' s_EhsHeader データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class s_EhsHeader


        Protected _LocationCode As String = String.Empty
        Protected _Item As String = String.Empty
        Protected _Text As String = String.Empty
        Protected _SortOrder As Integer = 0
        Protected _isRestockingControlSettings As Boolean = False
        Protected _isOutputTransferOrder As Boolean = False
        Protected _isOutputPriceRevision As Boolean = False
        Protected _CreatedBy As Integer = 0
        Protected _CreateDate As DateTime = New DateTime(0)
        Protected _UpdatedBy As Integer = 0
        Protected _UpdateDate As DateTime = New DateTime(0)

        ''' <summary> 
        ''' LocationCode を設定、または取得する 
        ''' </summary> 
        Public Property LocationCode() As String
            Get
                Return _LocationCode
            End Get
            Set(ByVal value As String)
                _LocationCode = value
            End Set
        End Property

        ''' <summary> 
        ''' Item を設定、または取得する 
        ''' </summary> 
        Public Property Item() As String
            Get
                Return _Item
            End Get
            Set(ByVal value As String)
                _Item = value
            End Set
        End Property

        ''' <summary> 
        ''' Text を設定、または取得する 
        ''' </summary> 
        Public Property Text() As String
            Get
                Return _Text
            End Get
            Set(ByVal value As String)
                _Text = value
            End Set
        End Property

        ''' <summary> 
        ''' SortOrder を設定、または取得する 
        ''' </summary> 
        Public Property SortOrder() As Integer
            Get
                Return _SortOrder
            End Get
            Set(ByVal value As Integer)
                _SortOrder = value
            End Set
        End Property

        ''' <summary> 
        ''' isRestockingControlSettings を設定、または取得する 
        ''' </summary> 
        Public Property isRestockingControlSettings() As Boolean
            Get
                Return _isRestockingControlSettings
            End Get
            Set(ByVal value As Boolean)
                _isRestockingControlSettings = value
            End Set
        End Property

        ''' <summary> 
        ''' isOutputTransferOrder を設定、または取得する 
        ''' </summary> 
        Public Property isOutputTransferOrder() As Boolean
            Get
                Return _isOutputTransferOrder
            End Get
            Set(ByVal value As Boolean)
                _isOutputTransferOrder = value
            End Set
        End Property

        ''' <summary> 
        ''' isOutputPriceRevision を設定、または取得する 
        ''' </summary> 
        Public Property isOutputPriceRevision() As Boolean
            Get
                Return _isOutputPriceRevision
            End Get
            Set(ByVal value As Boolean)
                _isOutputPriceRevision = value
            End Set
        End Property

        ''' <summary> 
        ''' CreatedBy を設定、または取得する 
        ''' </summary> 
        Public Property CreatedBy() As Integer
            Get
                Return _CreatedBy
            End Get
            Set(ByVal value As Integer)
                _CreatedBy = value
            End Set
        End Property

        ''' <summary> 
        ''' CreateDate を設定、または取得する 
        ''' </summary> 
        Public Property CreateDate() As DateTime
            Get
                Return _CreateDate
            End Get
            Set(ByVal value As DateTime)
                _CreateDate = value
            End Set
        End Property

        ''' <summary> 
        ''' UpdatedBy を設定、または取得する 
        ''' </summary> 
        Public Property UpdatedBy() As Integer
            Get
                Return _UpdatedBy
            End Get
            Set(ByVal value As Integer)
                _UpdatedBy = value
            End Set
        End Property

        ''' <summary> 
        ''' UpdateDate を設定、または取得する 
        ''' </summary> 
        Public Property UpdateDate() As DateTime
            Get
                Return _UpdateDate
            End Get
            Set(ByVal value As DateTime)
                _UpdateDate = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        ''' <param name="Item">Item</param>
        Public Sub Load(ByVal Item As String)

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [LocationCode],")
            Value.AppendLine("    [Item],")
            Value.AppendLine("    [Text],")
            Value.AppendLine("    [SortOrder],")
            Value.AppendLine("    [isRestockingControlSettings],")
            Value.AppendLine("    [isOutputTransferOrder],")
            Value.AppendLine("    [isOutputPriceRevision],")
            Value.AppendLine("    [CreatedBy],")
            Value.AppendLine("    [CreateDate],")
            Value.AppendLine("    [UpdatedBy],")
            Value.AppendLine("    [UpdateDate]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_EhsHeader]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [Item] = @Item")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.AddWithValue("Item", Item)
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("LocationCode"), _LocationCode)
                        SetProperty(DBReader("Item"), _Item)
                        SetProperty(DBReader("Text"), _Text)
                        SetProperty(DBReader("SortOrder"), _SortOrder)
                        SetProperty(DBReader("isRestockingControlSettings"), _isRestockingControlSettings)
                        SetProperty(DBReader("isOutputTransferOrder"), _isOutputTransferOrder)
                        SetProperty(DBReader("isOutputPriceRevision"), _isOutputPriceRevision)
                        SetProperty(DBReader("CreatedBy"), _CreatedBy)
                        SetProperty(DBReader("CreateDate"), _CreateDate)
                        SetProperty(DBReader("UpdatedBy"), _UpdatedBy)
                        SetProperty(DBReader("UpdateDate"), _UpdateDate)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        ''' <summary> 
        ''' データの存在チェックを行う。
        ''' </summary> 
        ''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        ''' <param name="Item">Item</param>
        Public Shared Function IsExists(ByVal Item As String) As Boolean

            ' データの存在チェックを行う SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    COUNT(*)")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_EhsHeader]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [Item] = @Item")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.Clear()
                    DBCommand.Parameters.AddWithValue("Item", Item)
                    DBConn.Open()
                    Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
                    Return i_Count > 0
                End Using
            End Using

        End Function

    End Class

    ''' <summary> 
    ''' s_EhsHeader リストクラス 
    ''' </summary> 
    Public Class s_EhsHeaderList
        Inherits List(Of s_EhsHeader)

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub

    End Class

End Namespace
