Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' s_NewProduct データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class s_NewProduct


        Protected _RegistryNumber As String = String.Empty
        Protected _ProductNumber As String = String.Empty
        Protected _ProposalDate As DateTime = New DateTime(0)
        Protected _isReProposal As Boolean = False
        Protected _StatusCode As String = String.Empty
        Protected _TestResult As String = String.Empty
        Protected _ProposalReasonID As Integer? = Nothing
        Protected _DeferralReasonID As Integer? = Nothing
        Protected _isNoDisplayWeb As Boolean = False
        Protected _ProposerID As Integer? = Nothing
        Protected _ProposalDeptCode As String = String.Empty
        Protected _ProjectID As String = String.Empty
        Protected _CAS As String = String.Empty
        Protected _RF As String = String.Empty
        Protected _MF As String = String.Empty
        Protected _MW As String = String.Empty
        Protected _ANH As String = String.Empty
        Protected _TEMPSTOR As String = String.Empty
        Protected _SciFinderHit As Integer? = Nothing
        Protected _isCONFIDENTIAL As Boolean = False
        Protected _isURGENT As Boolean = False
        Protected _ProductTypeCode As String = String.Empty
        Protected _isChromatoWeb As Boolean = False
        Protected _IMPORTHS As String = String.Empty
        Protected _IMPORTHSDATE As String = String.Empty
        Protected _OrderedFromCode As String = String.Empty
        Protected _OrderQuantity As String = String.Empty
        Protected _Information As String = String.Empty
        Protected _Note As String = String.Empty
        Protected _TestingNote As String = String.Empty
        Protected _RepackingNote As String = String.Empty
        Protected _Investigator As Integer? = Nothing
        Protected _InvestigationStartDate As DateTime = New DateTime(0)
        Protected _InvestigationDueDate As DateTime = New DateTime(0)
        Protected _InvestigationStatus As String = String.Empty
        Protected _InvestigationNote As String = String.Empty
        Protected _InvestigatorJP As Integer? = Nothing
        Protected _InvestigationStartDateJP As DateTime = New DateTime(0)
        Protected _InvestigationDueDateJP As DateTime = New DateTime(0)
        Protected _InvestigationStatusJP As String = String.Empty
        Protected _InvestigationNoteJP As String = String.Empty
        Protected _ChromatoEnName As String = String.Empty
        Protected _ChromatoJaName As String = String.Empty
        Protected _Sandbox As String = String.Empty
        Protected _PatDate As String = String.Empty
        Protected _PAT As String = String.Empty
        Protected _JUDGE As String = String.Empty
        Protected _REASON805 As String = String.Empty
        Protected _COM805 As String = String.Empty
        Protected _SALES As String = String.Empty
        Protected _PATNUM As String = String.Empty
        Protected _EXPDATE As String = String.Empty
        Protected _APPL As String = String.Empty
        Protected _FirstLit As String = String.Empty
        Protected _Patent As String = String.Empty
        Protected _PatentFamily As String = String.Empty
        Protected _isPatentJP As Integer? = Nothing
        Protected _ENCS As String = String.Empty
        Protected _SEIZOU As String = String.Empty
        Protected _TOKUTEI As String = String.Empty
        Protected _isMAYAKU As Boolean = False
        Protected _KOUSEI As String = String.Empty
        Protected _KOUSEITOU As String = String.Empty
        Protected _MAGEN As String = String.Empty
        Protected _isKAKUSEIZAI As Boolean = False
        Protected _KAKUSEIZAI As String = String.Empty
        Protected _SHITEI As String = String.Empty
        Protected _OZONE As String = String.Empty
        Protected _OZONENO As String = String.Empty
        Protected _OZONESY As String = String.Empty
        Protected _CWTOKU As String = String.Empty
        Protected _CWSITEI As String = String.Empty
        Protected _CWSITEISYU As String = String.Empty
        Protected _CSDEA As Integer? = Nothing
        Protected _CSSCH As String = String.Empty
        Protected _RSList As String = String.Empty
        Protected _RSDEA As Integer? = Nothing
        Protected _Reach As Integer? = Nothing
        Protected _CTSL As String = String.Empty
        Protected _CC As String = String.Empty
        Protected _CPC As String = String.Empty
        Protected _STIML As String = String.Empty
        Protected _NARCO As String = String.Empty
        Protected _PSYCHO As String = String.Empty
        Protected _CHIBAN As String = String.Empty
        Protected _EXPLOIM As String = String.Empty
        Protected _GASEXPLO As String = String.Empty
        Protected _SHANGBAN As String = String.Empty
        Protected _CreatedLocationCode As String = String.Empty
        Protected _SpecialFactor As Decimal? = Nothing
        Protected _CreatedBy As Integer = 0
        Protected _CreateDate As DateTime = New DateTime(0)
        Protected _UpdatedBy As Integer = 0
        Protected _UpdateDate As DateTime = New DateTime(0)

        ''' <summary> 
        ''' RegistryNumber を設定、または取得する 
        ''' </summary> 
        Public Property RegistryNumber() As String
            Get
                Return _RegistryNumber
            End Get
            Set(ByVal value As String)
                _RegistryNumber = value
            End Set
        End Property

        ''' <summary> 
        ''' ProductNumber を設定、または取得する 
        ''' </summary> 
        Public Property ProductNumber() As String
            Get
                Return _ProductNumber
            End Get
            Set(ByVal value As String)
                _ProductNumber = value
            End Set
        End Property

        ''' <summary> 
        ''' ProposalDate を設定、または取得する 
        ''' </summary> 
        Public Property ProposalDate() As DateTime
            Get
                Return _ProposalDate
            End Get
            Set(ByVal value As DateTime)
                _ProposalDate = value
            End Set
        End Property

        ''' <summary> 
        ''' isReProposal を設定、または取得する 
        ''' </summary> 
        Public Property isReProposal() As Boolean
            Get
                Return _isReProposal
            End Get
            Set(ByVal value As Boolean)
                _isReProposal = value
            End Set
        End Property

        ''' <summary> 
        ''' StatusCode を設定、または取得する 
        ''' </summary> 
        Public Property StatusCode() As String
            Get
                Return _StatusCode
            End Get
            Set(ByVal value As String)
                _StatusCode = value
            End Set
        End Property

        ''' <summary> 
        ''' TestResult を設定、または取得する 
        ''' </summary> 
        Public Property TestResult() As String
            Get
                Return _TestResult
            End Get
            Set(ByVal value As String)
                _TestResult = value
            End Set
        End Property

        ''' <summary> 
        ''' ProposalReasonID を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(ProposalReasonID.HasValue, ProposalReasonID, 0)
        '''     Dim val As Integer = ProposalReasonID.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property ProposalReasonID() As Integer?
            Get
                Return _ProposalReasonID
            End Get
            Set(ByVal value As Integer?)
                _ProposalReasonID = value
            End Set
        End Property

        ''' <summary> 
        ''' DeferralReasonID を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(DeferralReasonID.HasValue, DeferralReasonID, 0)
        '''     Dim val As Integer = DeferralReasonID.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property DeferralReasonID() As Integer?
            Get
                Return _DeferralReasonID
            End Get
            Set(ByVal value As Integer?)
                _DeferralReasonID = value
            End Set
        End Property

        ''' <summary> 
        ''' isNoDisplayWeb を設定、または取得する 
        ''' </summary> 
        Public Property isNoDisplayWeb() As Boolean
            Get
                Return _isNoDisplayWeb
            End Get
            Set(ByVal value As Boolean)
                _isNoDisplayWeb = value
            End Set
        End Property

        ''' <summary> 
        ''' ProposerID を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(ProposerID.HasValue, ProposerID, 0)
        '''     Dim val As Integer = ProposerID.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property ProposerID() As Integer?
            Get
                Return _ProposerID
            End Get
            Set(ByVal value As Integer?)
                _ProposerID = value
            End Set
        End Property

        ''' <summary> 
        ''' ProposalDeptCode を設定、または取得する 
        ''' </summary> 
        Public Property ProposalDeptCode() As String
            Get
                Return _ProposalDeptCode
            End Get
            Set(ByVal value As String)
                _ProposalDeptCode = value
            End Set
        End Property

        ''' <summary> 
        ''' ProjectID を設定、または取得する 
        ''' </summary> 
        Public Property ProjectID() As String
            Get
                Return _ProjectID
            End Get
            Set(ByVal value As String)
                _ProjectID = value
            End Set
        End Property

        ''' <summary> 
        ''' CAS を設定、または取得する 
        ''' </summary> 
        Public Property CAS() As String
            Get
                Return _CAS
            End Get
            Set(ByVal value As String)
                _CAS = value
            End Set
        End Property

        ''' <summary> 
        ''' RF を設定、または取得する 
        ''' </summary> 
        Public Property RF() As String
            Get
                Return _RF
            End Get
            Set(ByVal value As String)
                _RF = value
            End Set
        End Property

        ''' <summary> 
        ''' MF を設定、または取得する 
        ''' </summary> 
        Public Property MF() As String
            Get
                Return _MF
            End Get
            Set(ByVal value As String)
                _MF = value
            End Set
        End Property

        ''' <summary> 
        ''' MW を設定、または取得する 
        ''' </summary> 
        Public Property MW() As String
            Get
                Return _MW
            End Get
            Set(ByVal value As String)
                _MW = value
            End Set
        End Property

        ''' <summary> 
        ''' ANH を設定、または取得する 
        ''' </summary> 
        Public Property ANH() As String
            Get
                Return _ANH
            End Get
            Set(ByVal value As String)
                _ANH = value
            End Set
        End Property

        ''' <summary> 
        ''' TEMPSTOR を設定、または取得する 
        ''' </summary> 
        Public Property TEMPSTOR() As String
            Get
                Return _TEMPSTOR
            End Get
            Set(ByVal value As String)
                _TEMPSTOR = value
            End Set
        End Property

        ''' <summary> 
        ''' SciFinderHit を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(SciFinderHit.HasValue, SciFinderHit, 0)
        '''     Dim val As Integer = SciFinderHit.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property SciFinderHit() As Integer?
            Get
                Return _SciFinderHit
            End Get
            Set(ByVal value As Integer?)
                _SciFinderHit = value
            End Set
        End Property

        ''' <summary> 
        ''' isCONFIDENTIAL を設定、または取得する 
        ''' </summary> 
        Public Property isCONFIDENTIAL() As Boolean
            Get
                Return _isCONFIDENTIAL
            End Get
            Set(ByVal value As Boolean)
                _isCONFIDENTIAL = value
            End Set
        End Property

        ''' <summary> 
        ''' isURGENT を設定、または取得する 
        ''' </summary> 
        Public Property isURGENT() As Boolean
            Get
                Return _isURGENT
            End Get
            Set(ByVal value As Boolean)
                _isURGENT = value
            End Set
        End Property

        ''' <summary> 
        ''' ProductTypeCode を設定、または取得する 
        ''' </summary> 
        Public Property ProductTypeCode() As String
            Get
                Return _ProductTypeCode
            End Get
            Set(ByVal value As String)
                _ProductTypeCode = value
            End Set
        End Property

        ''' <summary> 
        ''' isChromatoWeb を設定、または取得する 
        ''' </summary> 
        Public Property isChromatoWeb() As Boolean
            Get
                Return _isChromatoWeb
            End Get
            Set(ByVal value As Boolean)
                _isChromatoWeb = value
            End Set
        End Property

        ''' <summary> 
        ''' IMPORTHS を設定、または取得する 
        ''' </summary> 
        Public Property IMPORTHS() As String
            Get
                Return _IMPORTHS
            End Get
            Set(ByVal value As String)
                _IMPORTHS = value
            End Set
        End Property

        ''' <summary> 
        ''' IMPORTHSDATE を設定、または取得する 
        ''' </summary> 
        Public Property IMPORTHSDATE() As String
            Get
                Return _IMPORTHSDATE
            End Get
            Set(ByVal value As String)
                _IMPORTHSDATE = value
            End Set
        End Property

        ''' <summary> 
        ''' OrderedFromCode を設定、または取得する 
        ''' </summary> 
        Public Property OrderedFromCode() As String
            Get
                Return _OrderedFromCode
            End Get
            Set(ByVal value As String)
                _OrderedFromCode = value
            End Set
        End Property

        ''' <summary> 
        ''' OrderQuantity を設定、または取得する 
        ''' </summary> 
        Public Property OrderQuantity() As String
            Get
                Return _OrderQuantity
            End Get
            Set(ByVal value As String)
                _OrderQuantity = value
            End Set
        End Property

        ''' <summary> 
        ''' Information を設定、または取得する 
        ''' </summary> 
        Public Property Information() As String
            Get
                Return _Information
            End Get
            Set(ByVal value As String)
                _Information = value
            End Set
        End Property

        ''' <summary> 
        ''' Note を設定、または取得する 
        ''' </summary> 
        Public Property Note() As String
            Get
                Return _Note
            End Get
            Set(ByVal value As String)
                _Note = value
            End Set
        End Property

        ''' <summary> 
        ''' TestingNote を設定、または取得する 
        ''' </summary> 
        Public Property TestingNote() As String
            Get
                Return _TestingNote
            End Get
            Set(ByVal value As String)
                _TestingNote = value
            End Set
        End Property

        ''' <summary> 
        ''' RepackingNote を設定、または取得する 
        ''' </summary> 
        Public Property RepackingNote() As String
            Get
                Return _RepackingNote
            End Get
            Set(ByVal value As String)
                _RepackingNote = value
            End Set
        End Property

        ''' <summary> 
        ''' Investigator を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(Investigator.HasValue, Investigator, 0)
        '''     Dim val As Integer = Investigator.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property Investigator() As Integer?
            Get
                Return _Investigator
            End Get
            Set(ByVal value As Integer?)
                _Investigator = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationStartDate を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationStartDate() As DateTime
            Get
                Return _InvestigationStartDate
            End Get
            Set(ByVal value As DateTime)
                _InvestigationStartDate = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationDueDate を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationDueDate() As DateTime
            Get
                Return _InvestigationDueDate
            End Get
            Set(ByVal value As DateTime)
                _InvestigationDueDate = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationStatus を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationStatus() As String
            Get
                Return _InvestigationStatus
            End Get
            Set(ByVal value As String)
                _InvestigationStatus = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationNote を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationNote() As String
            Get
                Return _InvestigationNote
            End Get
            Set(ByVal value As String)
                _InvestigationNote = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigatorJP を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(InvestigatorJP.HasValue, InvestigatorJP, 0)
        '''     Dim val As Integer = InvestigatorJP.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property InvestigatorJP() As Integer?
            Get
                Return _InvestigatorJP
            End Get
            Set(ByVal value As Integer?)
                _InvestigatorJP = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationStartDateJP を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationStartDateJP() As DateTime
            Get
                Return _InvestigationStartDateJP
            End Get
            Set(ByVal value As DateTime)
                _InvestigationStartDateJP = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationDueDateJP を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationDueDateJP() As DateTime
            Get
                Return _InvestigationDueDateJP
            End Get
            Set(ByVal value As DateTime)
                _InvestigationDueDateJP = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationStatusJP を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationStatusJP() As String
            Get
                Return _InvestigationStatusJP
            End Get
            Set(ByVal value As String)
                _InvestigationStatusJP = value
            End Set
        End Property

        ''' <summary> 
        ''' InvestigationNoteJP を設定、または取得する 
        ''' </summary> 
        Public Property InvestigationNoteJP() As String
            Get
                Return _InvestigationNoteJP
            End Get
            Set(ByVal value As String)
                _InvestigationNoteJP = value
            End Set
        End Property

        ''' <summary> 
        ''' ChromatoEnName を設定、または取得する 
        ''' </summary> 
        Public Property ChromatoEnName() As String
            Get
                Return _ChromatoEnName
            End Get
            Set(ByVal value As String)
                _ChromatoEnName = value
            End Set
        End Property

        ''' <summary> 
        ''' ChromatoJaName を設定、または取得する 
        ''' </summary> 
        Public Property ChromatoJaName() As String
            Get
                Return _ChromatoJaName
            End Get
            Set(ByVal value As String)
                _ChromatoJaName = value
            End Set
        End Property

        ''' <summary> 
        ''' Sandbox を設定、または取得する 
        ''' </summary> 
        Public Property Sandbox() As String
            Get
                Return _Sandbox
            End Get
            Set(ByVal value As String)
                _Sandbox = value
            End Set
        End Property

        ''' <summary> 
        ''' PatDate を設定、または取得する 
        ''' </summary> 
        Public Property PatDate() As String
            Get
                Return _PatDate
            End Get
            Set(ByVal value As String)
                _PatDate = value
            End Set
        End Property

        ''' <summary> 
        ''' PAT を設定、または取得する 
        ''' </summary> 
        Public Property PAT() As String
            Get
                Return _PAT
            End Get
            Set(ByVal value As String)
                _PAT = value
            End Set
        End Property

        ''' <summary> 
        ''' JUDGE を設定、または取得する 
        ''' </summary> 
        Public Property JUDGE() As String
            Get
                Return _JUDGE
            End Get
            Set(ByVal value As String)
                _JUDGE = value
            End Set
        End Property

        ''' <summary> 
        ''' REASON805 を設定、または取得する 
        ''' </summary> 
        Public Property REASON805() As String
            Get
                Return _REASON805
            End Get
            Set(ByVal value As String)
                _REASON805 = value
            End Set
        End Property

        ''' <summary> 
        ''' COM805 を設定、または取得する 
        ''' </summary> 
        Public Property COM805() As String
            Get
                Return _COM805
            End Get
            Set(ByVal value As String)
                _COM805 = value
            End Set
        End Property

        ''' <summary> 
        ''' SALES を設定、または取得する 
        ''' </summary> 
        Public Property SALES() As String
            Get
                Return _SALES
            End Get
            Set(ByVal value As String)
                _SALES = value
            End Set
        End Property

        ''' <summary> 
        ''' PATNUM を設定、または取得する 
        ''' </summary> 
        Public Property PATNUM() As String
            Get
                Return _PATNUM
            End Get
            Set(ByVal value As String)
                _PATNUM = value
            End Set
        End Property

        ''' <summary> 
        ''' EXPDATE を設定、または取得する 
        ''' </summary> 
        Public Property EXPDATE() As String
            Get
                Return _EXPDATE
            End Get
            Set(ByVal value As String)
                _EXPDATE = value
            End Set
        End Property

        ''' <summary> 
        ''' APPL を設定、または取得する 
        ''' </summary> 
        Public Property APPL() As String
            Get
                Return _APPL
            End Get
            Set(ByVal value As String)
                _APPL = value
            End Set
        End Property

        ''' <summary> 
        ''' FirstLit を設定、または取得する 
        ''' </summary> 
        Public Property FirstLit() As String
            Get
                Return _FirstLit
            End Get
            Set(ByVal value As String)
                _FirstLit = value
            End Set
        End Property

        ''' <summary> 
        ''' Patent を設定、または取得する 
        ''' </summary> 
        Public Property Patent() As String
            Get
                Return _Patent
            End Get
            Set(ByVal value As String)
                _Patent = value
            End Set
        End Property

        ''' <summary> 
        ''' PatentFamily を設定、または取得する 
        ''' </summary> 
        Public Property PatentFamily() As String
            Get
                Return _PatentFamily
            End Get
            Set(ByVal value As String)
                _PatentFamily = value
            End Set
        End Property

        ''' <summary> 
        ''' isPatentJP を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(isPatentJP.HasValue, isPatentJP, 0)
        '''     Dim val As Integer = isPatentJP.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property isPatentJP() As Integer?
            Get
                Return _isPatentJP
            End Get
            Set(ByVal value As Integer?)
                _isPatentJP = value
            End Set
        End Property

        ''' <summary> 
        ''' ENCS を設定、または取得する 
        ''' </summary> 
        Public Property ENCS() As String
            Get
                Return _ENCS
            End Get
            Set(ByVal value As String)
                _ENCS = value
            End Set
        End Property

        ''' <summary> 
        ''' SEIZOU を設定、または取得する 
        ''' </summary> 
        Public Property SEIZOU() As String
            Get
                Return _SEIZOU
            End Get
            Set(ByVal value As String)
                _SEIZOU = value
            End Set
        End Property

        ''' <summary> 
        ''' TOKUTEI を設定、または取得する 
        ''' </summary> 
        Public Property TOKUTEI() As String
            Get
                Return _TOKUTEI
            End Get
            Set(ByVal value As String)
                _TOKUTEI = value
            End Set
        End Property

        ''' <summary> 
        ''' isMAYAKU を設定、または取得する 
        ''' </summary> 
        Public Property isMAYAKU() As Boolean
            Get
                Return _isMAYAKU
            End Get
            Set(ByVal value As Boolean)
                _isMAYAKU = value
            End Set
        End Property

        ''' <summary> 
        ''' KOUSEI を設定、または取得する 
        ''' </summary> 
        Public Property KOUSEI() As String
            Get
                Return _KOUSEI
            End Get
            Set(ByVal value As String)
                _KOUSEI = value
            End Set
        End Property

        ''' <summary> 
        ''' KOUSEITOU を設定、または取得する 
        ''' </summary> 
        Public Property KOUSEITOU() As String
            Get
                Return _KOUSEITOU
            End Get
            Set(ByVal value As String)
                _KOUSEITOU = value
            End Set
        End Property

        ''' <summary> 
        ''' MAGEN を設定、または取得する 
        ''' </summary> 
        Public Property MAGEN() As String
            Get
                Return _MAGEN
            End Get
            Set(ByVal value As String)
                _MAGEN = value
            End Set
        End Property

        ''' <summary> 
        ''' isKAKUSEIZAI を設定、または取得する 
        ''' </summary> 
        Public Property isKAKUSEIZAI() As Boolean
            Get
                Return _isKAKUSEIZAI
            End Get
            Set(ByVal value As Boolean)
                _isKAKUSEIZAI = value
            End Set
        End Property

        ''' <summary> 
        ''' KAKUSEIZAI を設定、または取得する 
        ''' </summary> 
        Public Property KAKUSEIZAI() As String
            Get
                Return _KAKUSEIZAI
            End Get
            Set(ByVal value As String)
                _KAKUSEIZAI = value
            End Set
        End Property

        ''' <summary> 
        ''' SHITEI を設定、または取得する 
        ''' </summary> 
        Public Property SHITEI() As String
            Get
                Return _SHITEI
            End Get
            Set(ByVal value As String)
                _SHITEI = value
            End Set
        End Property

        ''' <summary> 
        ''' OZONE を設定、または取得する 
        ''' </summary> 
        Public Property OZONE() As String
            Get
                Return _OZONE
            End Get
            Set(ByVal value As String)
                _OZONE = value
            End Set
        End Property

        ''' <summary> 
        ''' OZONENO を設定、または取得する 
        ''' </summary> 
        Public Property OZONENO() As String
            Get
                Return _OZONENO
            End Get
            Set(ByVal value As String)
                _OZONENO = value
            End Set
        End Property

        ''' <summary> 
        ''' OZONESY を設定、または取得する 
        ''' </summary> 
        Public Property OZONESY() As String
            Get
                Return _OZONESY
            End Get
            Set(ByVal value As String)
                _OZONESY = value
            End Set
        End Property

        ''' <summary> 
        ''' CWTOKU を設定、または取得する 
        ''' </summary> 
        Public Property CWTOKU() As String
            Get
                Return _CWTOKU
            End Get
            Set(ByVal value As String)
                _CWTOKU = value
            End Set
        End Property

        ''' <summary> 
        ''' CWSITEI を設定、または取得する 
        ''' </summary> 
        Public Property CWSITEI() As String
            Get
                Return _CWSITEI
            End Get
            Set(ByVal value As String)
                _CWSITEI = value
            End Set
        End Property

        ''' <summary> 
        ''' CWSITEISYU を設定、または取得する 
        ''' </summary> 
        Public Property CWSITEISYU() As String
            Get
                Return _CWSITEISYU
            End Get
            Set(ByVal value As String)
                _CWSITEISYU = value
            End Set
        End Property

        ''' <summary> 
        ''' CSDEA を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(CSDEA.HasValue, CSDEA, 0)
        '''     Dim val As Integer = CSDEA.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property CSDEA() As Integer?
            Get
                Return _CSDEA
            End Get
            Set(ByVal value As Integer?)
                _CSDEA = value
            End Set
        End Property

        ''' <summary> 
        ''' CSSCH を設定、または取得する 
        ''' </summary> 
        Public Property CSSCH() As String
            Get
                Return _CSSCH
            End Get
            Set(ByVal value As String)
                _CSSCH = value
            End Set
        End Property

        ''' <summary> 
        ''' RSList を設定、または取得する 
        ''' </summary> 
        Public Property RSList() As String
            Get
                Return _RSList
            End Get
            Set(ByVal value As String)
                _RSList = value
            End Set
        End Property

        ''' <summary> 
        ''' RSDEA を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(RSDEA.HasValue, RSDEA, 0)
        '''     Dim val As Integer = RSDEA.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property RSDEA() As Integer?
            Get
                Return _RSDEA
            End Get
            Set(ByVal value As Integer?)
                _RSDEA = value
            End Set
        End Property

        ''' <summary> 
        ''' Reach を設定、または取得する 
        ''' <para>
        ''' ※ Integer 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Integer = IIf(Reach.HasValue, Reach, 0)
        '''     Dim val As Integer = Reach.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property Reach() As Integer?
            Get
                Return _Reach
            End Get
            Set(ByVal value As Integer?)
                _Reach = value
            End Set
        End Property

        ''' <summary> 
        ''' CTSL を設定、または取得する 
        ''' </summary> 
        Public Property CTSL() As String
            Get
                Return _CTSL
            End Get
            Set(ByVal value As String)
                _CTSL = value
            End Set
        End Property

        ''' <summary> 
        ''' CC を設定、または取得する 
        ''' </summary> 
        Public Property CC() As String
            Get
                Return _CC
            End Get
            Set(ByVal value As String)
                _CC = value
            End Set
        End Property

        ''' <summary> 
        ''' CPC を設定、または取得する 
        ''' </summary> 
        Public Property CPC() As String
            Get
                Return _CPC
            End Get
            Set(ByVal value As String)
                _CPC = value
            End Set
        End Property

        ''' <summary> 
        ''' STIML を設定、または取得する 
        ''' </summary> 
        Public Property STIML() As String
            Get
                Return _STIML
            End Get
            Set(ByVal value As String)
                _STIML = value
            End Set
        End Property

        ''' <summary> 
        ''' NARCO を設定、または取得する 
        ''' </summary> 
        Public Property NARCO() As String
            Get
                Return _NARCO
            End Get
            Set(ByVal value As String)
                _NARCO = value
            End Set
        End Property

        ''' <summary> 
        ''' PSYCHO を設定、または取得する 
        ''' </summary> 
        Public Property PSYCHO() As String
            Get
                Return _PSYCHO
            End Get
            Set(ByVal value As String)
                _PSYCHO = value
            End Set
        End Property

        ''' <summary> 
        ''' CHIBAN を設定、または取得する 
        ''' </summary> 
        Public Property CHIBAN() As String
            Get
                Return _CHIBAN
            End Get
            Set(ByVal value As String)
                _CHIBAN = value
            End Set
        End Property

        ''' <summary> 
        ''' EXPLOIM を設定、または取得する 
        ''' </summary> 
        Public Property EXPLOIM() As String
            Get
                Return _EXPLOIM
            End Get
            Set(ByVal value As String)
                _EXPLOIM = value
            End Set
        End Property

        ''' <summary> 
        ''' GASEXPLO を設定、または取得する 
        ''' </summary> 
        Public Property GASEXPLO() As String
            Get
                Return _GASEXPLO
            End Get
            Set(ByVal value As String)
                _GASEXPLO = value
            End Set
        End Property

        ''' <summary> 
        ''' SHANGBAN を設定、または取得する 
        ''' </summary> 
        Public Property SHANGBAN() As String
            Get
                Return _SHANGBAN
            End Get
            Set(ByVal value As String)
                _SHANGBAN = value
            End Set
        End Property

        ''' <summary> 
        ''' CreatedLocationCode を設定、または取得する 
        ''' </summary> 
        Public Property CreatedLocationCode() As String
            Get
                Return _CreatedLocationCode
            End Get
            Set(ByVal value As String)
                _CreatedLocationCode = value
            End Set
        End Property

        ''' <summary> 
        ''' SpecialFactor を設定、または取得する 
        ''' <para>
        ''' ※ Decimal 変数へ格納する場合は以下のようにすること。
        '''     Dim val As Decimal = IIf(SpecialFactor.HasValue, SpecialFactor, 0)
        '''     Dim val As Decimal = SpecialFactor.GetValueOrDefault() 
        ''' </para>
        ''' </summary> 
        Public Property SpecialFactor() As Decimal?
            Get
                Return _SpecialFactor
            End Get
            Set(ByVal value As Decimal?)
                _SpecialFactor = value
            End Set
        End Property

        ''' <summary> 
        ''' CreatedBy を設定、または取得する 
        ''' </summary> 
        Public Property CreatedBy() As Integer
            Get
                Return _CreatedBy
            End Get
            Set(ByVal value As Integer)
                _CreatedBy = value
            End Set
        End Property

        ''' <summary> 
        ''' CreateDate を設定、または取得する 
        ''' </summary> 
        Public Property CreateDate() As DateTime
            Get
                Return _CreateDate
            End Get
            Set(ByVal value As DateTime)
                _CreateDate = value
            End Set
        End Property

        ''' <summary> 
        ''' UpdatedBy を設定、または取得する 
        ''' </summary> 
        Public Property UpdatedBy() As Integer
            Get
                Return _UpdatedBy
            End Get
            Set(ByVal value As Integer)
                _UpdatedBy = value
            End Set
        End Property

        ''' <summary> 
        ''' UpdateDate を設定、または取得する 
        ''' </summary> 
        Public Property UpdateDate() As DateTime
            Get
                Return _UpdateDate
            End Get
            Set(ByVal value As DateTime)
                _UpdateDate = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        ''' <param name="RegistryNumber">RegistryNumber</param>
        Public Sub Load(ByVal RegistryNumber As String)

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [RegistryNumber],")
            Value.AppendLine("    [ProductNumber],")
            Value.AppendLine("    [ProposalDate],")
            Value.AppendLine("    [isReProposal],")
            Value.AppendLine("    [StatusCode],")
            Value.AppendLine("    [TestResult],")
            Value.AppendLine("    [ProposalReasonID],")
            Value.AppendLine("    [DeferralReasonID],")
            Value.AppendLine("    [isNoDisplayWeb],")
            Value.AppendLine("    [ProposerID],")
            Value.AppendLine("    [ProposalDeptCode],")
            Value.AppendLine("    [ProjectID],")
            Value.AppendLine("    [CAS],")
            Value.AppendLine("    [RF],")
            Value.AppendLine("    [MF],")
            Value.AppendLine("    [MW],")
            Value.AppendLine("    [ANH],")
            Value.AppendLine("    [TEMPSTOR],")
            Value.AppendLine("    [SciFinderHit],")
            Value.AppendLine("    [isCONFIDENTIAL],")
            Value.AppendLine("    [isURGENT],")
            Value.AppendLine("    [ProductTypeCode],")
            Value.AppendLine("    [isChromatoWeb],")
            Value.AppendLine("    [IMPORTHS],")
            Value.AppendLine("    [IMPORTHSDATE],")
            Value.AppendLine("    [OrderedFromCode],")
            Value.AppendLine("    [OrderQuantity],")
            Value.AppendLine("    [Information],")
            Value.AppendLine("    [Note],")
            Value.AppendLine("    [TestingNote],")
            Value.AppendLine("    [RepackingNote],")
            Value.AppendLine("    [Investigator],")
            Value.AppendLine("    [InvestigationStartDate],")
            Value.AppendLine("    [InvestigationDueDate],")
            Value.AppendLine("    [InvestigationStatus],")
            Value.AppendLine("    [InvestigationNote],")
            Value.AppendLine("    [InvestigatorJP],")
            Value.AppendLine("    [InvestigationStartDateJP],")
            Value.AppendLine("    [InvestigationDueDateJP],")
            Value.AppendLine("    [InvestigationStatusJP],")
            Value.AppendLine("    [InvestigationNoteJP],")
            Value.AppendLine("    [ChromatoEnName],")
            Value.AppendLine("    [ChromatoJaName],")
            Value.AppendLine("    [Sandbox],")
            Value.AppendLine("    [PatDate],")
            Value.AppendLine("    [PAT],")
            Value.AppendLine("    [JUDGE],")
            Value.AppendLine("    [REASON805],")
            Value.AppendLine("    [COM805],")
            Value.AppendLine("    [SALES],")
            Value.AppendLine("    [PATNUM],")
            Value.AppendLine("    [EXPDATE],")
            Value.AppendLine("    [APPL],")
            Value.AppendLine("    [FirstLit],")
            Value.AppendLine("    [Patent],")
            Value.AppendLine("    [PatentFamily],")
            Value.AppendLine("    [isPatentJP],")
            Value.AppendLine("    [ENCS],")
            Value.AppendLine("    [SEIZOU],")
            Value.AppendLine("    [TOKUTEI],")
            Value.AppendLine("    [isMAYAKU],")
            Value.AppendLine("    [KOUSEI],")
            Value.AppendLine("    [KOUSEITOU],")
            Value.AppendLine("    [MAGEN],")
            Value.AppendLine("    [isKAKUSEIZAI],")
            Value.AppendLine("    [KAKUSEIZAI],")
            Value.AppendLine("    [SHITEI],")
            Value.AppendLine("    [OZONE],")
            Value.AppendLine("    [OZONENO],")
            Value.AppendLine("    [OZONESY],")
            Value.AppendLine("    [CWTOKU],")
            Value.AppendLine("    [CWSITEI],")
            Value.AppendLine("    [CWSITEISYU],")
            Value.AppendLine("    [CSDEA],")
            Value.AppendLine("    [CSSCH],")
            Value.AppendLine("    [RSList],")
            Value.AppendLine("    [RSDEA],")
            Value.AppendLine("    [Reach],")
            Value.AppendLine("    [CTSL],")
            Value.AppendLine("    [CC],")
            Value.AppendLine("    [CPC],")
            Value.AppendLine("    [STIML],")
            Value.AppendLine("    [NARCO],")
            Value.AppendLine("    [PSYCHO],")
            Value.AppendLine("    [CHIBAN],")
            Value.AppendLine("    [EXPLOIM],")
            Value.AppendLine("    [GASEXPLO],")
            Value.AppendLine("    [SHANGBAN],")
            Value.AppendLine("    [CreatedLocationCode],")
            Value.AppendLine("    [SpecialFactor],")
            Value.AppendLine("    [CreatedBy],")
            Value.AppendLine("    [CreateDate],")
            Value.AppendLine("    [UpdatedBy],")
            Value.AppendLine("    [UpdateDate]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_NewProduct]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [RegistryNumber] = @RegistryNumber")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.AddWithValue("RegistryNumber", RegistryNumber)
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("RegistryNumber"), _RegistryNumber)
                        SetProperty(DBReader("ProductNumber"), _ProductNumber)
                        SetProperty(DBReader("ProposalDate"), _ProposalDate)
                        SetProperty(DBReader("isReProposal"), _isReProposal)
                        SetProperty(DBReader("StatusCode"), _StatusCode)
                        SetProperty(DBReader("TestResult"), _TestResult)
                        SetProperty(DBReader("ProposalReasonID"), _ProposalReasonID)
                        SetProperty(DBReader("DeferralReasonID"), _DeferralReasonID)
                        SetProperty(DBReader("isNoDisplayWeb"), _isNoDisplayWeb)
                        SetProperty(DBReader("ProposerID"), _ProposerID)
                        SetProperty(DBReader("ProposalDeptCode"), _ProposalDeptCode)
                        SetProperty(DBReader("ProjectID"), _ProjectID)
                        SetProperty(DBReader("CAS"), _CAS)
                        SetProperty(DBReader("RF"), _RF)
                        SetProperty(DBReader("MF"), _MF)
                        SetProperty(DBReader("MW"), _MW)
                        SetProperty(DBReader("ANH"), _ANH)
                        SetProperty(DBReader("TEMPSTOR"), _TEMPSTOR)
                        SetProperty(DBReader("SciFinderHit"), _SciFinderHit)
                        SetProperty(DBReader("isCONFIDENTIAL"), _isCONFIDENTIAL)
                        SetProperty(DBReader("isURGENT"), _isURGENT)
                        SetProperty(DBReader("ProductTypeCode"), _ProductTypeCode)
                        SetProperty(DBReader("isChromatoWeb"), _isChromatoWeb)
                        SetProperty(DBReader("IMPORTHS"), _IMPORTHS)
                        SetProperty(DBReader("IMPORTHSDATE"), _IMPORTHSDATE)
                        SetProperty(DBReader("OrderedFromCode"), _OrderedFromCode)
                        SetProperty(DBReader("OrderQuantity"), _OrderQuantity)
                        SetProperty(DBReader("Information"), _Information)
                        SetProperty(DBReader("Note"), _Note)
                        SetProperty(DBReader("TestingNote"), _TestingNote)
                        SetProperty(DBReader("RepackingNote"), _RepackingNote)
                        SetProperty(DBReader("Investigator"), _Investigator)
                        SetProperty(DBReader("InvestigationStartDate"), _InvestigationStartDate)
                        SetProperty(DBReader("InvestigationDueDate"), _InvestigationDueDate)
                        SetProperty(DBReader("InvestigationStatus"), _InvestigationStatus)
                        SetProperty(DBReader("InvestigationNote"), _InvestigationNote)
                        SetProperty(DBReader("InvestigatorJP"), _InvestigatorJP)
                        SetProperty(DBReader("InvestigationStartDateJP"), _InvestigationStartDateJP)
                        SetProperty(DBReader("InvestigationDueDateJP"), _InvestigationDueDateJP)
                        SetProperty(DBReader("InvestigationStatusJP"), _InvestigationStatusJP)
                        SetProperty(DBReader("InvestigationNoteJP"), _InvestigationNoteJP)
                        SetProperty(DBReader("ChromatoEnName"), _ChromatoEnName)
                        SetProperty(DBReader("ChromatoJaName"), _ChromatoJaName)
                        SetProperty(DBReader("Sandbox"), _Sandbox)
                        SetProperty(DBReader("PatDate"), _PatDate)
                        SetProperty(DBReader("PAT"), _PAT)
                        SetProperty(DBReader("JUDGE"), _JUDGE)
                        SetProperty(DBReader("REASON805"), _REASON805)
                        SetProperty(DBReader("COM805"), _COM805)
                        SetProperty(DBReader("SALES"), _SALES)
                        SetProperty(DBReader("PATNUM"), _PATNUM)
                        SetProperty(DBReader("EXPDATE"), _EXPDATE)
                        SetProperty(DBReader("APPL"), _APPL)
                        SetProperty(DBReader("FirstLit"), _FirstLit)
                        SetProperty(DBReader("Patent"), _Patent)
                        SetProperty(DBReader("PatentFamily"), _PatentFamily)
                        SetProperty(DBReader("isPatentJP"), _isPatentJP)
                        SetProperty(DBReader("ENCS"), _ENCS)
                        SetProperty(DBReader("SEIZOU"), _SEIZOU)
                        SetProperty(DBReader("TOKUTEI"), _TOKUTEI)
                        SetProperty(DBReader("isMAYAKU"), _isMAYAKU)
                        SetProperty(DBReader("KOUSEI"), _KOUSEI)
                        SetProperty(DBReader("KOUSEITOU"), _KOUSEITOU)
                        SetProperty(DBReader("MAGEN"), _MAGEN)
                        SetProperty(DBReader("isKAKUSEIZAI"), _isKAKUSEIZAI)
                        SetProperty(DBReader("KAKUSEIZAI"), _KAKUSEIZAI)
                        SetProperty(DBReader("SHITEI"), _SHITEI)
                        SetProperty(DBReader("OZONE"), _OZONE)
                        SetProperty(DBReader("OZONENO"), _OZONENO)
                        SetProperty(DBReader("OZONESY"), _OZONESY)
                        SetProperty(DBReader("CWTOKU"), _CWTOKU)
                        SetProperty(DBReader("CWSITEI"), _CWSITEI)
                        SetProperty(DBReader("CWSITEISYU"), _CWSITEISYU)
                        SetProperty(DBReader("CSDEA"), _CSDEA)
                        SetProperty(DBReader("CSSCH"), _CSSCH)
                        SetProperty(DBReader("RSList"), _RSList)
                        SetProperty(DBReader("RSDEA"), _RSDEA)
                        SetProperty(DBReader("Reach"), _Reach)
                        SetProperty(DBReader("CTSL"), _CTSL)
                        SetProperty(DBReader("CC"), _CC)
                        SetProperty(DBReader("CPC"), _CPC)
                        SetProperty(DBReader("STIML"), _STIML)
                        SetProperty(DBReader("NARCO"), _NARCO)
                        SetProperty(DBReader("PSYCHO"), _PSYCHO)
                        SetProperty(DBReader("CHIBAN"), _CHIBAN)
                        SetProperty(DBReader("EXPLOIM"), _EXPLOIM)
                        SetProperty(DBReader("GASEXPLO"), _GASEXPLO)
                        SetProperty(DBReader("SHANGBAN"), _SHANGBAN)
                        SetProperty(DBReader("CreatedLocationCode"), _CreatedLocationCode)
                        SetProperty(DBReader("SpecialFactor"), _SpecialFactor)
                        SetProperty(DBReader("CreatedBy"), _CreatedBy)
                        SetProperty(DBReader("CreateDate"), _CreateDate)
                        SetProperty(DBReader("UpdatedBy"), _UpdatedBy)
                        SetProperty(DBReader("UpdateDate"), _UpdateDate)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub

        ''' <summary> 
        ''' データの存在チェックを行う。
        ''' </summary> 
        ''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        ''' <param name="RegistryNumber">RegistryNumber</param>
        Public Shared Function IsExists(ByVal RegistryNumber As String) As Boolean

            ' データの存在チェックを行う SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    COUNT(*)")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_NewProduct]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [RegistryNumber] = @RegistryNumber")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.Clear()
                    DBCommand.Parameters.AddWithValue("RegistryNumber", RegistryNumber)
                    DBConn.Open()
                    Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
                    Return i_Count > 0
                End Using
            End Using

        End Function

    End Class

    ''' <summary> 
    ''' s_NewProduct リストクラス 
    ''' </summary> 
    Public Class s_NewProductList
        Inherits List(Of s_NewProduct)

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub

    End Class

End Namespace
