Option Explicit On
Option Infer Off
Option Strict On

Imports System.Text
Imports System.Data.SqlClient
Imports System.Text.RegularExpressions
Imports Purchase.TCIDataAccess.DBCommon

Namespace TCIDataAccess

    ''' <summary> 
    ''' s_SPECS データクラス 
    ''' </summary> 
    ''' <remarks>
    ''' <para>Generated by データクラス自動生成ツール Ver 4.1</para>
    ''' </remarks>
    Public Class s_SPECS


        Protected _MATNR As String = String.Empty
        Protected _CAS As String = String.Empty
        Protected _RF As String = String.Empty
        Protected _PURITY As String = String.Empty
        Protected _SG As String = String.Empty
        Protected _STORAGE As String = String.Empty
        Protected _DELI As String = String.Empty
        Protected _FZSHIP As String = String.Empty
        Protected _UNNUM As String = String.Empty
        Protected _UNCLASS As String = String.Empty
        Protected _UNSUB As String = String.Empty
        Protected _LIM2 As String = String.Empty
        Protected _LIM0 As String = String.Empty
        Protected _LIM1 As String = String.Empty
        Protected _SNOEX As String = String.Empty
        Protected _INOEX As String = String.Empty
        Protected _CWSITEI As String = String.Empty
        Protected _CWSITEISYU As String = String.Empty
        Protected _PRE As String = String.Empty
        Protected _SPITEM As String = String.Empty
        Protected _COM805 As String = String.Empty
        Protected _ENCSNUM As String = String.Empty
        Protected _PD As String = String.Empty
        Protected _MAGEN As String = String.Empty
        Protected _HS_J As String = String.Empty
        Protected _ENCS As String = String.Empty
        Protected _KOUSEI As String = String.Empty
        Protected _KAKUSEIZAI As String = String.Empty
        Protected _SHITEI As String = String.Empty
        Protected _OZONE As String = String.Empty
        Protected _SEIZOU As String = String.Empty
        Protected _CATPUB As String = String.Empty
        Protected _REPFLAG As String = String.Empty
        Protected _FLAG As String = String.Empty
        Protected _DCSNUM As String = String.Empty
        Protected _CCC As String = String.Empty
        Protected _IMI As String = String.Empty
        Protected _CPC As String = String.Empty
        Protected _CTSL As String = String.Empty
        Protected _DGLQ As String = String.Empty
        Protected _TSCA As String = String.Empty
        Protected _RES1 As String = String.Empty
        Protected _RES2 As String = String.Empty
        Protected _RES3 As String = String.Empty
        Protected _RES4 As String = String.Empty
        Protected _HS_A As String = String.Empty
        Protected _IFC As String = String.Empty
        Protected _HAZ As String = String.Empty
        Protected _EUREG As String = String.Empty
        Protected _ECNUM As String = String.Empty
        Protected _SVHC As String = String.Empty
        Protected _HS_E As String = String.Empty
        Protected _LQVAL As String = String.Empty
        Protected _EQ As String = String.Empty
        Protected _NDPS As String = String.Empty
        Protected _EXPORT As String = String.Empty
        Protected _ECSC As String = String.Empty
        Protected _CC As String = String.Empty
        Protected _IPL As String = String.Empty
        Protected _HS_I As String = String.Empty
        Protected _FIREG As String = String.Empty
        Protected _FIRESG As String = String.Empty
        Protected _FIRECLASS As String = String.Empty
        Protected _FIRESYU As String = String.Empty
        Protected _AVOID As String = String.Empty
        Protected _UNPG As String = String.Empty
        Protected _CA_MAXNET As String = String.Empty
        Protected _CA_PI As String = String.Empty
        Protected _PA1_MAXNET As String = String.Empty
        Protected _PA1_PI As String = String.Empty
        Protected _EXPCTRL As String = String.Empty

        ''' <summary> 
        ''' MATNR を設定、または取得する 
        ''' </summary> 
        Public Property MATNR() As String
            Get
                Return _MATNR
            End Get
            Set(ByVal value As String)
                _MATNR = value
            End Set
        End Property

        ''' <summary> 
        ''' CAS を設定、または取得する 
        ''' </summary> 
        Public Property CAS() As String
            Get
                Return _CAS
            End Get
            Set(ByVal value As String)
                _CAS = value
            End Set
        End Property

        ''' <summary> 
        ''' RF を設定、または取得する 
        ''' </summary> 
        Public Property RF() As String
            Get
                Return _RF
            End Get
            Set(ByVal value As String)
                _RF = value
            End Set
        End Property

        ''' <summary> 
        ''' PURITY を設定、または取得する 
        ''' </summary> 
        Public Property PURITY() As String
            Get
                Return _PURITY
            End Get
            Set(ByVal value As String)
                _PURITY = value
            End Set
        End Property

        ''' <summary> 
        ''' SG を設定、または取得する 
        ''' </summary> 
        Public Property SG() As String
            Get
                Return _SG
            End Get
            Set(ByVal value As String)
                _SG = value
            End Set
        End Property

        ''' <summary> 
        ''' STORAGE を設定、または取得する 
        ''' </summary> 
        Public Property STORAGE() As String
            Get
                Return _STORAGE
            End Get
            Set(ByVal value As String)
                _STORAGE = value
            End Set
        End Property

        ''' <summary> 
        ''' DELI を設定、または取得する 
        ''' </summary> 
        Public Property DELI() As String
            Get
                Return _DELI
            End Get
            Set(ByVal value As String)
                _DELI = value
            End Set
        End Property

        ''' <summary> 
        ''' FZSHIP を設定、または取得する 
        ''' </summary> 
        Public Property FZSHIP() As String
            Get
                Return _FZSHIP
            End Get
            Set(ByVal value As String)
                _FZSHIP = value
            End Set
        End Property

        ''' <summary> 
        ''' UNNUM を設定、または取得する 
        ''' </summary> 
        Public Property UNNUM() As String
            Get
                Return _UNNUM
            End Get
            Set(ByVal value As String)
                _UNNUM = value
            End Set
        End Property

        ''' <summary> 
        ''' UNCLASS を設定、または取得する 
        ''' </summary> 
        Public Property UNCLASS() As String
            Get
                Return _UNCLASS
            End Get
            Set(ByVal value As String)
                _UNCLASS = value
            End Set
        End Property

        ''' <summary> 
        ''' UNSUB を設定、または取得する 
        ''' </summary> 
        Public Property UNSUB() As String
            Get
                Return _UNSUB
            End Get
            Set(ByVal value As String)
                _UNSUB = value
            End Set
        End Property

        ''' <summary> 
        ''' LIM2 を設定、または取得する 
        ''' </summary> 
        Public Property LIM2() As String
            Get
                Return _LIM2
            End Get
            Set(ByVal value As String)
                _LIM2 = value
            End Set
        End Property

        ''' <summary> 
        ''' LIM0 を設定、または取得する 
        ''' </summary> 
        Public Property LIM0() As String
            Get
                Return _LIM0
            End Get
            Set(ByVal value As String)
                _LIM0 = value
            End Set
        End Property

        ''' <summary> 
        ''' LIM1 を設定、または取得する 
        ''' </summary> 
        Public Property LIM1() As String
            Get
                Return _LIM1
            End Get
            Set(ByVal value As String)
                _LIM1 = value
            End Set
        End Property

        ''' <summary> 
        ''' SNOEX を設定、または取得する 
        ''' </summary> 
        Public Property SNOEX() As String
            Get
                Return _SNOEX
            End Get
            Set(ByVal value As String)
                _SNOEX = value
            End Set
        End Property

        ''' <summary> 
        ''' INOEX を設定、または取得する 
        ''' </summary> 
        Public Property INOEX() As String
            Get
                Return _INOEX
            End Get
            Set(ByVal value As String)
                _INOEX = value
            End Set
        End Property

        ''' <summary> 
        ''' CWSITEI を設定、または取得する 
        ''' </summary> 
        Public Property CWSITEI() As String
            Get
                Return _CWSITEI
            End Get
            Set(ByVal value As String)
                _CWSITEI = value
            End Set
        End Property

        ''' <summary> 
        ''' CWSITEISYU を設定、または取得する 
        ''' </summary> 
        Public Property CWSITEISYU() As String
            Get
                Return _CWSITEISYU
            End Get
            Set(ByVal value As String)
                _CWSITEISYU = value
            End Set
        End Property

        ''' <summary> 
        ''' PRE を設定、または取得する 
        ''' </summary> 
        Public Property PRE() As String
            Get
                Return _PRE
            End Get
            Set(ByVal value As String)
                _PRE = value
            End Set
        End Property

        ''' <summary> 
        ''' SPITEM を設定、または取得する 
        ''' </summary> 
        Public Property SPITEM() As String
            Get
                Return _SPITEM
            End Get
            Set(ByVal value As String)
                _SPITEM = value
            End Set
        End Property

        ''' <summary> 
        ''' COM805 を設定、または取得する 
        ''' </summary> 
        Public Property COM805() As String
            Get
                Return _COM805
            End Get
            Set(ByVal value As String)
                _COM805 = value
            End Set
        End Property

        ''' <summary> 
        ''' ENCSNUM を設定、または取得する 
        ''' </summary> 
        Public Property ENCSNUM() As String
            Get
                Return _ENCSNUM
            End Get
            Set(ByVal value As String)
                _ENCSNUM = value
            End Set
        End Property

        ''' <summary> 
        ''' PD を設定、または取得する 
        ''' </summary> 
        Public Property PD() As String
            Get
                Return _PD
            End Get
            Set(ByVal value As String)
                _PD = value
            End Set
        End Property

        ''' <summary> 
        ''' MAGEN を設定、または取得する 
        ''' </summary> 
        Public Property MAGEN() As String
            Get
                Return _MAGEN
            End Get
            Set(ByVal value As String)
                _MAGEN = value
            End Set
        End Property

        ''' <summary> 
        ''' HS_J を設定、または取得する 
        ''' </summary> 
        Public Property HS_J() As String
            Get
                Return _HS_J
            End Get
            Set(ByVal value As String)
                _HS_J = value
            End Set
        End Property

        ''' <summary> 
        ''' ENCS を設定、または取得する 
        ''' </summary> 
        Public Property ENCS() As String
            Get
                Return _ENCS
            End Get
            Set(ByVal value As String)
                _ENCS = value
            End Set
        End Property

        ''' <summary> 
        ''' KOUSEI を設定、または取得する 
        ''' </summary> 
        Public Property KOUSEI() As String
            Get
                Return _KOUSEI
            End Get
            Set(ByVal value As String)
                _KOUSEI = value
            End Set
        End Property

        ''' <summary> 
        ''' KAKUSEIZAI を設定、または取得する 
        ''' </summary> 
        Public Property KAKUSEIZAI() As String
            Get
                Return _KAKUSEIZAI
            End Get
            Set(ByVal value As String)
                _KAKUSEIZAI = value
            End Set
        End Property

        ''' <summary> 
        ''' SHITEI を設定、または取得する 
        ''' </summary> 
        Public Property SHITEI() As String
            Get
                Return _SHITEI
            End Get
            Set(ByVal value As String)
                _SHITEI = value
            End Set
        End Property

        ''' <summary> 
        ''' OZONE を設定、または取得する 
        ''' </summary> 
        Public Property OZONE() As String
            Get
                Return _OZONE
            End Get
            Set(ByVal value As String)
                _OZONE = value
            End Set
        End Property

        ''' <summary> 
        ''' SEIZOU を設定、または取得する 
        ''' </summary> 
        Public Property SEIZOU() As String
            Get
                Return _SEIZOU
            End Get
            Set(ByVal value As String)
                _SEIZOU = value
            End Set
        End Property

        ''' <summary> 
        ''' CATPUB を設定、または取得する 
        ''' </summary> 
        Public Property CATPUB() As String
            Get
                Return _CATPUB
            End Get
            Set(ByVal value As String)
                _CATPUB = value
            End Set
        End Property

        ''' <summary> 
        ''' REPFLAG を設定、または取得する 
        ''' </summary> 
        Public Property REPFLAG() As String
            Get
                Return _REPFLAG
            End Get
            Set(ByVal value As String)
                _REPFLAG = value
            End Set
        End Property

        ''' <summary> 
        ''' FLAG を設定、または取得する 
        ''' </summary> 
        Public Property FLAG() As String
            Get
                Return _FLAG
            End Get
            Set(ByVal value As String)
                _FLAG = value
            End Set
        End Property

        ''' <summary> 
        ''' DCSNUM を設定、または取得する 
        ''' </summary> 
        Public Property DCSNUM() As String
            Get
                Return _DCSNUM
            End Get
            Set(ByVal value As String)
                _DCSNUM = value
            End Set
        End Property

        ''' <summary> 
        ''' CCC を設定、または取得する 
        ''' </summary> 
        Public Property CCC() As String
            Get
                Return _CCC
            End Get
            Set(ByVal value As String)
                _CCC = value
            End Set
        End Property

        ''' <summary> 
        ''' IMI を設定、または取得する 
        ''' </summary> 
        Public Property IMI() As String
            Get
                Return _IMI
            End Get
            Set(ByVal value As String)
                _IMI = value
            End Set
        End Property

        ''' <summary> 
        ''' CPC を設定、または取得する 
        ''' </summary> 
        Public Property CPC() As String
            Get
                Return _CPC
            End Get
            Set(ByVal value As String)
                _CPC = value
            End Set
        End Property

        ''' <summary> 
        ''' CTSL を設定、または取得する 
        ''' </summary> 
        Public Property CTSL() As String
            Get
                Return _CTSL
            End Get
            Set(ByVal value As String)
                _CTSL = value
            End Set
        End Property

        ''' <summary> 
        ''' DGLQ を設定、または取得する 
        ''' </summary> 
        Public Property DGLQ() As String
            Get
                Return _DGLQ
            End Get
            Set(ByVal value As String)
                _DGLQ = value
            End Set
        End Property

        ''' <summary> 
        ''' TSCA を設定、または取得する 
        ''' </summary> 
        Public Property TSCA() As String
            Get
                Return _TSCA
            End Get
            Set(ByVal value As String)
                _TSCA = value
            End Set
        End Property

        ''' <summary> 
        ''' RES1 を設定、または取得する 
        ''' </summary> 
        Public Property RES1() As String
            Get
                Return _RES1
            End Get
            Set(ByVal value As String)
                _RES1 = value
            End Set
        End Property

        ''' <summary> 
        ''' RES2 を設定、または取得する 
        ''' </summary> 
        Public Property RES2() As String
            Get
                Return _RES2
            End Get
            Set(ByVal value As String)
                _RES2 = value
            End Set
        End Property

        ''' <summary> 
        ''' RES3 を設定、または取得する 
        ''' </summary> 
        Public Property RES3() As String
            Get
                Return _RES3
            End Get
            Set(ByVal value As String)
                _RES3 = value
            End Set
        End Property

        ''' <summary> 
        ''' RES4 を設定、または取得する 
        ''' </summary> 
        Public Property RES4() As String
            Get
                Return _RES4
            End Get
            Set(ByVal value As String)
                _RES4 = value
            End Set
        End Property

        ''' <summary> 
        ''' HS_A を設定、または取得する 
        ''' </summary> 
        Public Property HS_A() As String
            Get
                Return _HS_A
            End Get
            Set(ByVal value As String)
                _HS_A = value
            End Set
        End Property

        ''' <summary> 
        ''' IFC を設定、または取得する 
        ''' </summary> 
        Public Property IFC() As String
            Get
                Return _IFC
            End Get
            Set(ByVal value As String)
                _IFC = value
            End Set
        End Property

        ''' <summary> 
        ''' HAZ を設定、または取得する 
        ''' </summary> 
        Public Property HAZ() As String
            Get
                Return _HAZ
            End Get
            Set(ByVal value As String)
                _HAZ = value
            End Set
        End Property

        ''' <summary> 
        ''' EUREG を設定、または取得する 
        ''' </summary> 
        Public Property EUREG() As String
            Get
                Return _EUREG
            End Get
            Set(ByVal value As String)
                _EUREG = value
            End Set
        End Property

        ''' <summary> 
        ''' ECNUM を設定、または取得する 
        ''' </summary> 
        Public Property ECNUM() As String
            Get
                Return _ECNUM
            End Get
            Set(ByVal value As String)
                _ECNUM = value
            End Set
        End Property

        ''' <summary> 
        ''' SVHC を設定、または取得する 
        ''' </summary> 
        Public Property SVHC() As String
            Get
                Return _SVHC
            End Get
            Set(ByVal value As String)
                _SVHC = value
            End Set
        End Property

        ''' <summary> 
        ''' HS_E を設定、または取得する 
        ''' </summary> 
        Public Property HS_E() As String
            Get
                Return _HS_E
            End Get
            Set(ByVal value As String)
                _HS_E = value
            End Set
        End Property

        ''' <summary> 
        ''' LQVAL を設定、または取得する 
        ''' </summary> 
        Public Property LQVAL() As String
            Get
                Return _LQVAL
            End Get
            Set(ByVal value As String)
                _LQVAL = value
            End Set
        End Property

        ''' <summary> 
        ''' EQ を設定、または取得する 
        ''' </summary> 
        Public Property EQ() As String
            Get
                Return _EQ
            End Get
            Set(ByVal value As String)
                _EQ = value
            End Set
        End Property

        ''' <summary> 
        ''' NDPS を設定、または取得する 
        ''' </summary> 
        Public Property NDPS() As String
            Get
                Return _NDPS
            End Get
            Set(ByVal value As String)
                _NDPS = value
            End Set
        End Property

        ''' <summary> 
        ''' EXPORT を設定、または取得する 
        ''' </summary> 
        Public Property EXPORT() As String
            Get
                Return _EXPORT
            End Get
            Set(ByVal value As String)
                _EXPORT = value
            End Set
        End Property

        ''' <summary> 
        ''' ECSC を設定、または取得する 
        ''' </summary> 
        Public Property ECSC() As String
            Get
                Return _ECSC
            End Get
            Set(ByVal value As String)
                _ECSC = value
            End Set
        End Property

        ''' <summary> 
        ''' CC を設定、または取得する 
        ''' </summary> 
        Public Property CC() As String
            Get
                Return _CC
            End Get
            Set(ByVal value As String)
                _CC = value
            End Set
        End Property

        ''' <summary> 
        ''' IPL を設定、または取得する 
        ''' </summary> 
        Public Property IPL() As String
            Get
                Return _IPL
            End Get
            Set(ByVal value As String)
                _IPL = value
            End Set
        End Property

        ''' <summary> 
        ''' HS_I を設定、または取得する 
        ''' </summary> 
        Public Property HS_I() As String
            Get
                Return _HS_I
            End Get
            Set(ByVal value As String)
                _HS_I = value
            End Set
        End Property

        ''' <summary> 
        ''' FIREG を設定、または取得する 
        ''' </summary> 
        Public Property FIREG() As String
            Get
                Return _FIREG
            End Get
            Set(ByVal value As String)
                _FIREG = value
            End Set
        End Property

        ''' <summary> 
        ''' FIRESG を設定、または取得する 
        ''' </summary> 
        Public Property FIRESG() As String
            Get
                Return _FIRESG
            End Get
            Set(ByVal value As String)
                _FIRESG = value
            End Set
        End Property

        ''' <summary> 
        ''' FIRECLASS を設定、または取得する 
        ''' </summary> 
        Public Property FIRECLASS() As String
            Get
                Return _FIRECLASS
            End Get
            Set(ByVal value As String)
                _FIRECLASS = value
            End Set
        End Property

        ''' <summary> 
        ''' FIRESYU を設定、または取得する 
        ''' </summary> 
        Public Property FIRESYU() As String
            Get
                Return _FIRESYU
            End Get
            Set(ByVal value As String)
                _FIRESYU = value
            End Set
        End Property

        ''' <summary> 
        ''' AVOID を設定、または取得する 
        ''' </summary> 
        Public Property AVOID() As String
            Get
                Return _AVOID
            End Get
            Set(ByVal value As String)
                _AVOID = value
            End Set
        End Property

        ''' <summary> 
        ''' UNPG を設定、または取得する 
        ''' </summary> 
        Public Property UNPG() As String
            Get
                Return _UNPG
            End Get
            Set(ByVal value As String)
                _UNPG = value
            End Set
        End Property

        ''' <summary> 
        ''' CA_MAXNET を設定、または取得する 
        ''' </summary> 
        Public Property CA_MAXNET() As String
            Get
                Return _CA_MAXNET
            End Get
            Set(ByVal value As String)
                _CA_MAXNET = value
            End Set
        End Property

        ''' <summary> 
        ''' CA_PI を設定、または取得する 
        ''' </summary> 
        Public Property CA_PI() As String
            Get
                Return _CA_PI
            End Get
            Set(ByVal value As String)
                _CA_PI = value
            End Set
        End Property

        ''' <summary> 
        ''' PA1_MAXNET を設定、または取得する 
        ''' </summary> 
        Public Property PA1_MAXNET() As String
            Get
                Return _PA1_MAXNET
            End Get
            Set(ByVal value As String)
                _PA1_MAXNET = value
            End Set
        End Property

        ''' <summary> 
        ''' PA1_PI を設定、または取得する 
        ''' </summary> 
        Public Property PA1_PI() As String
            Get
                Return _PA1_PI
            End Get
            Set(ByVal value As String)
                _PA1_PI = value
            End Set
        End Property

        ''' <summary>
        ''' EXPCTRL を設定、または取得する
        ''' </summary>
        Public Property EXPCTRL() As String
            Get
                Return _EXPCTRL
            End Get
            Set(ByVal value As String)
                _EXPCTRL = value
            End Set
        End Property

        ''' <summary> 
        ''' コンストラクタ
        ''' </summary> 
        Public Sub New()

        End Sub

        ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        Public Sub Load()

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [MATNR],")
            Value.AppendLine("    [CAS],")
            Value.AppendLine("    [RF],")
            Value.AppendLine("    [PURITY],")
            Value.AppendLine("    [SG],")
            Value.AppendLine("    [STORAGE],")
            Value.AppendLine("    [DELI],")
            Value.AppendLine("    [FZSHIP],")
            Value.AppendLine("    [UNNUM],")
            Value.AppendLine("    [UNCLASS],")
            Value.AppendLine("    [UNSUB],")
            Value.AppendLine("    [LIM2],")
            Value.AppendLine("    [LIM0],")
            Value.AppendLine("    [LIM1],")
            Value.AppendLine("    [SNOEX],")
            Value.AppendLine("    [INOEX],")
            Value.AppendLine("    [CWSITEI],")
            Value.AppendLine("    [CWSITEISYU],")
            Value.AppendLine("    [PRE],")
            Value.AppendLine("    [SPITEM],")
            Value.AppendLine("    [COM805],")
            Value.AppendLine("    [ENCSNUM],")
            Value.AppendLine("    [PD],")
            Value.AppendLine("    [MAGEN],")
            Value.AppendLine("    [HS_J],")
            Value.AppendLine("    [ENCS],")
            Value.AppendLine("    [KOUSEI],")
            Value.AppendLine("    [KAKUSEIZAI],")
            Value.AppendLine("    [SHITEI],")
            Value.AppendLine("    [OZONE],")
            Value.AppendLine("    [SEIZOU],")
            Value.AppendLine("    [CATPUB],")
            Value.AppendLine("    [REPFLAG],")
            Value.AppendLine("    [FLAG],")
            Value.AppendLine("    [DCSNUM],")
            Value.AppendLine("    [CCC],")
            Value.AppendLine("    [IMI],")
            Value.AppendLine("    [CPC],")
            Value.AppendLine("    [CTSL],")
            Value.AppendLine("    [DGLQ],")
            Value.AppendLine("    [TSCA],")
            Value.AppendLine("    [RES1],")
            Value.AppendLine("    [RES2],")
            Value.AppendLine("    [RES3],")
            Value.AppendLine("    [RES4],")
            Value.AppendLine("    [HS_A],")
            Value.AppendLine("    [IFC],")
            Value.AppendLine("    [HAZ],")
            Value.AppendLine("    [EUREG],")
            Value.AppendLine("    [ECNUM],")
            Value.AppendLine("    [SVHC],")
            Value.AppendLine("    [HS_E],")
            Value.AppendLine("    [LQVAL],")
            Value.AppendLine("    [EQ],")
            Value.AppendLine("    [NDPS],")
            Value.AppendLine("    [EXPORT],")
            Value.AppendLine("    [ECSC],")
            Value.AppendLine("    [CC],")
            Value.AppendLine("    [IPL],")
            Value.AppendLine("    [HS_I],")
            Value.AppendLine("    [FIREG],")
            Value.AppendLine("    [FIRESG],")
            Value.AppendLine("    [FIRECLASS],")
            Value.AppendLine("    [FIRESYU],")
            Value.AppendLine("    [AVOID],")
            Value.AppendLine("    [UNPG],")
            Value.AppendLine("    [CA_MAXNET],")
            Value.AppendLine("    [CA_PI],")
            Value.AppendLine("    [PA1_MAXNET],")
            Value.AppendLine("    [PA1_PI],")
            Value.AppendLine("    [EXPCTRL]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_SPECS]")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("MATNR"), _MATNR)
                        SetProperty(DBReader("CAS"), _CAS)
                        SetProperty(DBReader("RF"), _RF)
                        SetProperty(DBReader("PURITY"), _PURITY)
                        SetProperty(DBReader("SG"), _SG)
                        SetProperty(DBReader("STORAGE"), _STORAGE)
                        SetProperty(DBReader("DELI"), _DELI)
                        SetProperty(DBReader("FZSHIP"), _FZSHIP)
                        SetProperty(DBReader("UNNUM"), _UNNUM)
                        SetProperty(DBReader("UNCLASS"), _UNCLASS)
                        SetProperty(DBReader("UNSUB"), _UNSUB)
                        SetProperty(DBReader("LIM2"), _LIM2)
                        SetProperty(DBReader("LIM0"), _LIM0)
                        SetProperty(DBReader("LIM1"), _LIM1)
                        SetProperty(DBReader("SNOEX"), _SNOEX)
                        SetProperty(DBReader("INOEX"), _INOEX)
                        SetProperty(DBReader("CWSITEI"), _CWSITEI)
                        SetProperty(DBReader("CWSITEISYU"), _CWSITEISYU)
                        SetProperty(DBReader("PRE"), _PRE)
                        SetProperty(DBReader("SPITEM"), _SPITEM)
                        SetProperty(DBReader("COM805"), _COM805)
                        SetProperty(DBReader("ENCSNUM"), _ENCSNUM)
                        SetProperty(DBReader("PD"), _PD)
                        SetProperty(DBReader("MAGEN"), _MAGEN)
                        SetProperty(DBReader("HS_J"), _HS_J)
                        SetProperty(DBReader("ENCS"), _ENCS)
                        SetProperty(DBReader("KOUSEI"), _KOUSEI)
                        SetProperty(DBReader("KAKUSEIZAI"), _KAKUSEIZAI)
                        SetProperty(DBReader("SHITEI"), _SHITEI)
                        SetProperty(DBReader("OZONE"), _OZONE)
                        SetProperty(DBReader("SEIZOU"), _SEIZOU)
                        SetProperty(DBReader("CATPUB"), _CATPUB)
                        SetProperty(DBReader("REPFLAG"), _REPFLAG)
                        SetProperty(DBReader("FLAG"), _FLAG)
                        SetProperty(DBReader("DCSNUM"), _DCSNUM)
                        SetProperty(DBReader("CCC"), _CCC)
                        SetProperty(DBReader("IMI"), _IMI)
                        SetProperty(DBReader("CPC"), _CPC)
                        SetProperty(DBReader("CTSL"), _CTSL)
                        SetProperty(DBReader("DGLQ"), _DGLQ)
                        SetProperty(DBReader("TSCA"), _TSCA)
                        SetProperty(DBReader("RES1"), _RES1)
                        SetProperty(DBReader("RES2"), _RES2)
                        SetProperty(DBReader("RES3"), _RES3)
                        SetProperty(DBReader("RES4"), _RES4)
                        SetProperty(DBReader("HS_A"), _HS_A)
                        SetProperty(DBReader("IFC"), _IFC)
                        SetProperty(DBReader("HAZ"), _HAZ)
                        SetProperty(DBReader("EUREG"), _EUREG)
                        SetProperty(DBReader("ECNUM"), _ECNUM)
                        SetProperty(DBReader("SVHC"), _SVHC)
                        SetProperty(DBReader("HS_E"), _HS_E)
                        SetProperty(DBReader("LQVAL"), _LQVAL)
                        SetProperty(DBReader("EQ"), _EQ)
                        SetProperty(DBReader("NDPS"), _NDPS)
                        SetProperty(DBReader("EXPORT"), _EXPORT)
                        SetProperty(DBReader("ECSC"), _ECSC)
                        SetProperty(DBReader("CC"), _CC)
                        SetProperty(DBReader("IPL"), _IPL)
                        SetProperty(DBReader("HS_I"), _HS_I)
                        SetProperty(DBReader("FIREG"), _FIREG)
                        SetProperty(DBReader("FIRESG"), _FIRESG)
                        SetProperty(DBReader("FIRECLASS"), _FIRECLASS)
                        SetProperty(DBReader("FIRESYU"), _FIRESYU)
                        SetProperty(DBReader("AVOID"), _AVOID)
                        SetProperty(DBReader("UNPG"), _UNPG)
                        SetProperty(DBReader("CA_MAXNET"), _CA_MAXNET)
                        SetProperty(DBReader("CA_PI"), _CA_PI)
                        SetProperty(DBReader("PA1_MAXNET"), _PA1_MAXNET)
                        SetProperty(DBReader("PA1_PI"), _PA1_PI)
                        SetProperty(DBReader("EXPCTRL"), _EXPCTRL)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub
                ''' <summary>
        ''' データベースからデータを読み込む。
        ''' </summary>
        Public Sub Load(ProductNumber As String)

            'データベースからデータを読み込む SQL 文字列を生成する。
            Dim Value As New StringBuilder()
            Value.AppendLine("SELECT")
            Value.AppendLine("    [MATNR],")
            Value.AppendLine("    [CAS],")
            Value.AppendLine("    [RF],")
            Value.AppendLine("    [PURITY],")
            Value.AppendLine("    [SG],")
            Value.AppendLine("    [STORAGE],")
            Value.AppendLine("    [DELI],")
            Value.AppendLine("    [FZSHIP],")
            Value.AppendLine("    [UNNUM],")
            Value.AppendLine("    [UNCLASS],")
            Value.AppendLine("    [UNSUB],")
            Value.AppendLine("    [LIM2],")
            Value.AppendLine("    [LIM0],")
            Value.AppendLine("    [LIM1],")
            Value.AppendLine("    [SNOEX],")
            Value.AppendLine("    [INOEX],")
            Value.AppendLine("    [CWSITEI],")
            Value.AppendLine("    [CWSITEISYU],")
            Value.AppendLine("    [PRE],")
            Value.AppendLine("    [SPITEM],")
            Value.AppendLine("    [COM805],")
            Value.AppendLine("    [ENCSNUM],")
            Value.AppendLine("    [PD],")
            Value.AppendLine("    [MAGEN],")
            Value.AppendLine("    [HS_J],")
            Value.AppendLine("    [ENCS],")
            Value.AppendLine("    [KOUSEI],")
            Value.AppendLine("    [KAKUSEIZAI],")
            Value.AppendLine("    [SHITEI],")
            Value.AppendLine("    [OZONE],")
            Value.AppendLine("    [SEIZOU],")
            Value.AppendLine("    [CATPUB],")
            Value.AppendLine("    [REPFLAG],")
            Value.AppendLine("    [FLAG],")
            Value.AppendLine("    [DCSNUM],")
            Value.AppendLine("    [CCC],")
            Value.AppendLine("    [IMI],")
            Value.AppendLine("    [CPC],")
            Value.AppendLine("    [CTSL],")
            Value.AppendLine("    [DGLQ],")
            Value.AppendLine("    [TSCA],")
            Value.AppendLine("    [RES1],")
            Value.AppendLine("    [RES2],")
            Value.AppendLine("    [RES3],")
            Value.AppendLine("    [RES4],")
            Value.AppendLine("    [HS_A],")
            Value.AppendLine("    [IFC],")
            Value.AppendLine("    [HAZ],")
            Value.AppendLine("    [EUREG],")
            Value.AppendLine("    [ECNUM],")
            Value.AppendLine("    [SVHC],")
            Value.AppendLine("    [HS_E],")
            Value.AppendLine("    [LQVAL],")
            Value.AppendLine("    [EQ],")
            Value.AppendLine("    [NDPS],")
            Value.AppendLine("    [EXPORT],")
            Value.AppendLine("    [ECSC],")
            Value.AppendLine("    [CC],")
            Value.AppendLine("    [IPL],")
            Value.AppendLine("    [HS_I],")
            Value.AppendLine("    [FIREG],")
            Value.AppendLine("    [FIRESG],")
            Value.AppendLine("    [FIRECLASS],")
            Value.AppendLine("    [FIRESYU],")
            Value.AppendLine("    [AVOID],")
            Value.AppendLine("    [UNPG],")
            Value.AppendLine("    [CA_MAXNET],")
            Value.AppendLine("    [CA_PI],")
            Value.AppendLine("    [PA1_MAXNET],")
            Value.AppendLine("    [PA1_PI],")
            Value.AppendLine("    [EXPCTRL]")
            Value.AppendLine("FROM")
            Value.AppendLine("    [s_SPECS]")
            Value.AppendLine("WHERE")
            Value.AppendLine("    [MATNR] = @ProductNumber")

            Using DBConn As New SqlConnection(DB_CONNECT_STRING)
                Using DBCommand As SqlCommand = DBConn.CreateCommand()
                    DBCommand.CommandText = Value.ToString()
                    DBCommand.Parameters.Clear()
                    DBCommand.Parameters.AddWithValue("productNumber", ProductNumber)
                    DBConn.Open()
                    Dim DBReader As SqlDataReader = DBCommand.ExecuteReader()
                    While DBReader.Read()
                        SetProperty(DBReader("MATNR"), _MATNR)
                        SetProperty(DBReader("CAS"), _CAS)
                        SetProperty(DBReader("RF"), _RF)
                        SetProperty(DBReader("PURITY"), _PURITY)
                        SetProperty(DBReader("SG"), _SG)
                        SetProperty(DBReader("STORAGE"), _STORAGE)
                        SetProperty(DBReader("DELI"), _DELI)
                        SetProperty(DBReader("FZSHIP"), _FZSHIP)
                        SetProperty(DBReader("UNNUM"), _UNNUM)
                        SetProperty(DBReader("UNCLASS"), _UNCLASS)
                        SetProperty(DBReader("UNSUB"), _UNSUB)
                        SetProperty(DBReader("LIM2"), _LIM2)
                        SetProperty(DBReader("LIM0"), _LIM0)
                        SetProperty(DBReader("LIM1"), _LIM1)
                        SetProperty(DBReader("SNOEX"), _SNOEX)
                        SetProperty(DBReader("INOEX"), _INOEX)
                        SetProperty(DBReader("CWSITEI"), _CWSITEI)
                        SetProperty(DBReader("CWSITEISYU"), _CWSITEISYU)
                        SetProperty(DBReader("PRE"), _PRE)
                        SetProperty(DBReader("SPITEM"), _SPITEM)
                        SetProperty(DBReader("COM805"), _COM805)
                        SetProperty(DBReader("ENCSNUM"), _ENCSNUM)
                        SetProperty(DBReader("PD"), _PD)
                        SetProperty(DBReader("MAGEN"), _MAGEN)
                        SetProperty(DBReader("HS_J"), _HS_J)
                        SetProperty(DBReader("ENCS"), _ENCS)
                        SetProperty(DBReader("KOUSEI"), _KOUSEI)
                        SetProperty(DBReader("KAKUSEIZAI"), _KAKUSEIZAI)
                        SetProperty(DBReader("SHITEI"), _SHITEI)
                        SetProperty(DBReader("OZONE"), _OZONE)
                        SetProperty(DBReader("SEIZOU"), _SEIZOU)
                        SetProperty(DBReader("CATPUB"), _CATPUB)
                        SetProperty(DBReader("REPFLAG"), _REPFLAG)
                        SetProperty(DBReader("FLAG"), _FLAG)
                        SetProperty(DBReader("DCSNUM"), _DCSNUM)
                        SetProperty(DBReader("CCC"), _CCC)
                        SetProperty(DBReader("IMI"), _IMI)
                        SetProperty(DBReader("CPC"), _CPC)
                        SetProperty(DBReader("CTSL"), _CTSL)
                        SetProperty(DBReader("DGLQ"), _DGLQ)
                        SetProperty(DBReader("TSCA"), _TSCA)
                        SetProperty(DBReader("RES1"), _RES1)
                        SetProperty(DBReader("RES2"), _RES2)
                        SetProperty(DBReader("RES3"), _RES3)
                        SetProperty(DBReader("RES4"), _RES4)
                        SetProperty(DBReader("HS_A"), _HS_A)
                        SetProperty(DBReader("IFC"), _IFC)
                        SetProperty(DBReader("HAZ"), _HAZ)
                        SetProperty(DBReader("EUREG"), _EUREG)
                        SetProperty(DBReader("ECNUM"), _ECNUM)
                        SetProperty(DBReader("SVHC"), _SVHC)
                        SetProperty(DBReader("HS_E"), _HS_E)
                        SetProperty(DBReader("LQVAL"), _LQVAL)
                        SetProperty(DBReader("EQ"), _EQ)
                        SetProperty(DBReader("NDPS"), _NDPS)
                        SetProperty(DBReader("EXPORT"), _EXPORT)
                        SetProperty(DBReader("ECSC"), _ECSC)
                        SetProperty(DBReader("CC"), _CC)
                        SetProperty(DBReader("IPL"), _IPL)
                        SetProperty(DBReader("HS_I"), _HS_I)
                        SetProperty(DBReader("FIREG"), _FIREG)
                        SetProperty(DBReader("FIRESG"), _FIRESG)
                        SetProperty(DBReader("FIRECLASS"), _FIRECLASS)
                        SetProperty(DBReader("FIRESYU"), _FIRESYU)
                        SetProperty(DBReader("AVOID"), _AVOID)
                        SetProperty(DBReader("UNPG"), _UNPG)
                        SetProperty(DBReader("CA_MAXNET"), _CA_MAXNET)
                        SetProperty(DBReader("CA_PI"), _CA_PI)
                        SetProperty(DBReader("PA1_MAXNET"), _PA1_MAXNET)
                        SetProperty(DBReader("PA1_PI"), _PA1_PI)
                        SetProperty(DBReader("EXPCTRL"), _EXPCTRL)
                    End While
                    DBReader.Close()
                End Using
            End Using

        End Sub
        '''' <summary> 
        '''' データの存在チェックを行う。
        '''' </summary> 
        '''' <returns>存在する場合は True、しない場合は False を返す</returns> 
        'Public Shared Function IsExists() As Boolean

        '    ' データの存在チェックを行う SQL 文字列を生成する。
        '    Dim Value As New StringBuilder()
        '    Value.AppendLine("SELECT")
        '    Value.AppendLine("    COUNT(*)")
        '    Value.AppendLine("FROM")
        '    Value.AppendLine("    [s_SPECS]")

        '    Using DBConn As New SqlConnection(DB_CONNECT_STRING)
        '        Using DBCommand As SqlCommand = DBConn.CreateCommand()
        '            DBCommand.CommandText = Value.ToString()
        '            DBCommand.Parameters.Clear()
        '            DBConn.Open()
        '            Dim i_Count As Integer = Convert.ToInt32(DBCommand.ExecuteScalar())
        '            Return i_Count > 0
        '        End Using
        '    End Using

        'End Function

    End Class

    ''' <summary> 
    ''' s_SPECS リストクラス 
    ''' </summary> 
    Public Class s_SPECSList
        Inherits List(Of s_SPECS)

        ''' <summary>
        ''' コンストラクタ
        ''' </summary>
        Public Sub New()

        End Sub

    End Class

End Namespace
